# Generated by Django 5.0.6 on 2025-12-26 02:05

import apps.personnel.models.certification
import apps.personnel.models.medical
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0005_countrymodel_distributorcenter_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("OPERATIONS", "Operaciones"),
                            ("ADMINISTRATION", "Administración"),
                            ("PEOPLE", "People/RRHH"),
                            ("SECURITY", "Seguridad"),
                            ("DELIVERY", "Delivery/Despachos"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Código de área",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "db_table": "personnel_area",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CertificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la certificación",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "validity_period_days",
                    models.IntegerField(
                        default=365,
                        help_text="Días hasta que expire la certificación",
                        verbose_name="Período de validez (días)",
                    ),
                ),
                (
                    "requires_renewal",
                    models.BooleanField(
                        default=True, verbose_name="Requiere renovación"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Certificación obligatoria para ciertos puestos",
                        verbose_name="Es obligatoria",
                    ),
                ),
                (
                    "applicable_positions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de position_type donde aplica",
                        verbose_name="Posiciones aplicables",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Certificación",
                "verbose_name_plural": "Tipos de Certificación",
                "db_table": "personnel_certification_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del departamento"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Código",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="personnel.area",
                        verbose_name="Área",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "personnel_department",
                "ordering": ["area", "name"],
                "unique_together": {("area", "code")},
            },
        ),
        migrations.CreateModel(
            name="PersonnelProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        help_text="Código único del empleado (ej: 22144, SUP001, OPM042)",
                        max_length=20,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Código de empleado",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contacto (no necesariamente tiene usuario en sistema)",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.CharField(
                        choices=[
                            ("OPERATIVE", "Operativo (Picker/Contador/OPM)"),
                            ("SUPERVISOR", "Supervisor"),
                            ("AREA_MANAGER", "Jefe de Área"),
                            ("CD_MANAGER", "Gerente de Centro de Distribución"),
                        ],
                        db_index=True,
                        default="OPERATIVE",
                        max_length=20,
                        verbose_name="Nivel jerárquico",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Título del puesto (ej: Supervisor de Turno Noche)",
                        max_length=100,
                        verbose_name="Puesto actual",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("PICKER", "Picker"),
                            ("COUNTER", "Contador"),
                            ("OPM", "Operador de Montacargas"),
                            ("YARD_DRIVER", "Conductor de Patio"),
                            ("LOADER", "Cargador"),
                            ("WAREHOUSE_ASSISTANT", "Ayudante de Almacén"),
                            ("SECURITY_GUARD", "Guardia de Seguridad"),
                            ("DELIVERY_DRIVER", "Conductor de Delivery"),
                            ("ADMINISTRATIVE", "Administrativo"),
                            ("OTHER", "Otro"),
                        ],
                        help_text="Categoría general del puesto",
                        max_length=30,
                        verbose_name="Tipo de posición",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Fecha de ingreso")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanente"),
                            ("TEMPORARY", "Temporal"),
                            ("CONTRACT", "Contrato"),
                        ],
                        default="PERMANENT",
                        max_length=50,
                        verbose_name="Tipo de contrato",
                    ),
                ),
                (
                    "personal_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(13)],
                        verbose_name="Número de identidad",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Fecha de nacimiento")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=10,
                        verbose_name="Género",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Soltero/a"),
                            ("MARRIED", "Casado/a"),
                            ("DIVORCED", "Divorciado/a"),
                            ("WIDOWED", "Viudo/a"),
                            ("UNION", "Unión libre"),
                        ],
                        max_length=20,
                        verbose_name="Estado civil",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número de teléfono inválido",
                                regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email personal"
                    ),
                ),
                ("address", models.TextField(verbose_name="Dirección residencial")),
                ("city", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "shirt_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "2XL"),
                            ("XXXL", "3XL"),
                        ],
                        max_length=10,
                        verbose_name="Talla de camisa",
                    ),
                ),
                (
                    "pants_size",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 32, 34, 36",
                        max_length=10,
                        verbose_name="Talla de pantalón",
                    ),
                ),
                (
                    "shoe_size",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 8, 9, 10",
                        max_length=10,
                        verbose_name="Talla de zapatos",
                    ),
                ),
                (
                    "glove_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        max_length=10,
                        verbose_name="Talla de guantes",
                    ),
                ),
                (
                    "helmet_size",
                    models.CharField(
                        blank=True,
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=10,
                        verbose_name="Talla de casco",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de terminación"
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(blank=True, verbose_name="Motivo de terminación"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas adicionales"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnel",
                        to="personnel.area",
                        verbose_name="Área de negocio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personnel_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnel",
                        to="personnel.department",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "distributor_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnel",
                        to="maintenance.distributorcenter",
                        verbose_name="Centro de distribución",
                    ),
                ),
                (
                    "immediate_supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "hierarchy_level__in": [
                                "SUPERVISOR",
                                "AREA_MANAGER",
                                "CD_MANAGER",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_personnel",
                        to="personnel.personnelprofile",
                        verbose_name="Supervisor inmediato",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Usuario del sistema (solo para personal con acceso a la plataforma)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnel_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Personal",
                "verbose_name_plural": "Perfiles de Personal",
                "db_table": "personnel_profile",
                "ordering": ["-is_active", "first_name", "last_name"],
                "permissions": [
                    ("view_all_personnel", "Puede ver todo el personal"),
                    ("manage_personnel", "Puede gestionar personal"),
                    ("view_sensitive_data", "Puede ver datos sensibles"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_date",
                    models.DateField(db_index=True, verbose_name="Fecha de la métrica"),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diario"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                        ],
                        db_index=True,
                        default="DAILY",
                        max_length=10,
                        verbose_name="Período",
                    ),
                ),
                (
                    "pallets_moved",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad de pallets procesados",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Pallets movidos",
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas trabajadas",
                    ),
                ),
                (
                    "productivity_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pallets por hora (calculado automáticamente)",
                        max_digits=6,
                        null=True,
                        verbose_name="Tasa de productividad",
                    ),
                ),
                (
                    "errors_count",
                    models.IntegerField(
                        default=0,
                        help_text="Errores o incidencias registradas",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cantidad de errores",
                    ),
                ),
                (
                    "accidents_count",
                    models.IntegerField(
                        default=0,
                        help_text="Accidentes de trabajo",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Accidentes",
                    ),
                ),
                (
                    "supervisor_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Escala de 1 a 5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación del supervisor",
                    ),
                ),
                (
                    "supervisor_comments",
                    models.TextField(
                        blank=True, verbose_name="Comentarios del supervisor"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas adicionales"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_given",
                        to="personnel.personnelprofile",
                        verbose_name="Evaluado por",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="personnel.personnelprofile",
                        verbose_name="Personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrica de Desempeño",
                "verbose_name_plural": "Métricas de Desempeño",
                "db_table": "personnel_performance_metric",
                "ordering": ["-metric_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("CONDITION", "Condición Médica"),
                            ("CLINIC_PASS", "Pase de Clínica"),
                            ("INCAPACITY", "Incapacidad"),
                            ("CHECKUP", "Chequeo Médico"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de registro",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(db_index=True, verbose_name="Fecha del registro"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción general del evento médico",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True,
                        help_text="Diagnóstico médico (si aplica)",
                        verbose_name="Diagnóstico",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Para incapacidades o tratamientos",
                        null=True,
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha esperada de retorno",
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre del médico"
                    ),
                ),
                (
                    "clinic_hospital",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Clínica/Hospital"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="PDF o imagen del documento médico",
                        null=True,
                        upload_to=apps.personnel.models.medical.medical_document_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Documento médico",
                    ),
                ),
                (
                    "requires_followup",
                    models.BooleanField(
                        default=False, verbose_name="Requiere seguimiento"
                    ),
                ),
                (
                    "followup_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de seguimiento"
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=True,
                        help_text="Solo accesible por personal autorizado",
                        verbose_name="Confidencial",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas adicionales"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_records_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="personnel.personnelprofile",
                        verbose_name="Personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Médico",
                "verbose_name_plural": "Registros Médicos",
                "db_table": "personnel_medical_record",
                "ordering": ["-record_date"],
                "permissions": [
                    (
                        "view_confidential_medical",
                        "Puede ver registros médicos confidenciales",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre completo"),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("SPOUSE", "Cónyuge"),
                            ("PARENT", "Padre/Madre"),
                            ("SIBLING", "Hermano/a"),
                            ("CHILD", "Hijo/a"),
                            ("FRIEND", "Amigo/a"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Relación",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número de teléfono inválido",
                                regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                            )
                        ],
                        verbose_name="Teléfono principal",
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número de teléfono inválido",
                                regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                            )
                        ],
                        verbose_name="Teléfono alternativo",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Contacto principal"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas adicionales"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="personnel.personnelprofile",
                        verbose_name="Personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto de Emergencia",
                "verbose_name_plural": "Contactos de Emergencia",
                "db_table": "personnel_emergency_contact",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de registro o identificación del certificado",
                        max_length=100,
                        verbose_name="Número de certificación",
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        help_text="Institución que emite el certificado",
                        max_length=200,
                        verbose_name="Autoridad emisora",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(db_index=True, verbose_name="Fecha de emisión"),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        db_index=True, verbose_name="Fecha de vencimiento"
                    ),
                ),
                (
                    "certificate_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.personnel.models.certification.certification_document_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Documento del certificado",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Si la certificación está vigente y válida",
                        verbose_name="Válida",
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(default=False, verbose_name="Revocada"),
                ),
                (
                    "revocation_reason",
                    models.TextField(blank=True, verbose_name="Motivo de revocación"),
                ),
                (
                    "revocation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de revocación"
                    ),
                ),
                (
                    "renewal_notification_sent",
                    models.BooleanField(
                        default=False, verbose_name="Notificación de renovación enviada"
                    ),
                ),
                (
                    "renewal_notification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de notificación"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "certification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certifications",
                        to="personnel.certificationtype",
                        verbose_name="Tipo de certificación",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="personnel.personnelprofile",
                        verbose_name="Personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificación",
                "verbose_name_plural": "Certificaciones",
                "db_table": "personnel_certification",
                "ordering": ["-expiration_date"],
            },
        ),
        migrations.AddIndex(
            model_name="personnelprofile",
            index=models.Index(
                fields=["employee_code"], name="personnel_p_employe_a3d2b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personnelprofile",
            index=models.Index(
                fields=["hierarchy_level"], name="personnel_p_hierarc_e4d7e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personnelprofile",
            index=models.Index(
                fields=["is_active"], name="personnel_p_is_acti_96f89f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personnelprofile",
            index=models.Index(
                fields=["distributor_center", "is_active"],
                name="personnel_p_distrib_d9d60c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personnelprofile",
            index=models.Index(
                fields=["area", "is_active"], name="personnel_p_area_id_badd5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["personnel", "-metric_date"],
                name="personnel_p_personn_b2e708_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["period", "-metric_date"], name="personnel_p_period_584c51_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performancemetric",
            unique_together={("personnel", "metric_date", "period")},
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["personnel", "-record_date"],
                name="personnel_m_personn_7728d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["record_type", "-record_date"],
                name="personnel_m_record__d8dd8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["personnel", "-expiration_date"],
                name="personnel_c_personn_aac960_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["is_valid", "expiration_date"],
                name="personnel_c_is_vali_e71c04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["certification_type", "is_valid"],
                name="personnel_c_certifi_76b926_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certification",
            unique_together={
                ("personnel", "certification_type", "certification_number")
            },
        ),
    ]
