# Generated by Django 5.0.6 on 2025-12-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="certification",
            new_name="app_personn_personn_d82057_idx",
            old_name="personnel_c_personn_aac960_idx",
        ),
        migrations.RenameIndex(
            model_name="certification",
            new_name="app_personn_is_vali_31fc92_idx",
            old_name="personnel_c_is_vali_e71c04_idx",
        ),
        migrations.RenameIndex(
            model_name="certification",
            new_name="app_personn_certifi_6b21fb_idx",
            old_name="personnel_c_certifi_76b926_idx",
        ),
        migrations.RenameIndex(
            model_name="medicalrecord",
            new_name="app_personn_personn_f09db1_idx",
            old_name="personnel_m_personn_7728d5_idx",
        ),
        migrations.RenameIndex(
            model_name="medicalrecord",
            new_name="app_personn_record__1b177c_idx",
            old_name="personnel_m_record__d8dd8e_idx",
        ),
        migrations.RenameIndex(
            model_name="performancemetric",
            new_name="app_personn_personn_142067_idx",
            old_name="personnel_p_personn_b2e708_idx",
        ),
        migrations.RenameIndex(
            model_name="performancemetric",
            new_name="app_personn_period_88bd7e_idx",
            old_name="personnel_p_period_584c51_idx",
        ),
        migrations.RenameIndex(
            model_name="personnelprofile",
            new_name="app_personn_employe_57b372_idx",
            old_name="personnel_p_employe_a3d2b0_idx",
        ),
        migrations.RenameIndex(
            model_name="personnelprofile",
            new_name="app_personn_hierarc_9d941a_idx",
            old_name="personnel_p_hierarc_e4d7e6_idx",
        ),
        migrations.RenameIndex(
            model_name="personnelprofile",
            new_name="app_personn_is_acti_c4ba9a_idx",
            old_name="personnel_p_is_acti_96f89f_idx",
        ),
        migrations.RenameIndex(
            model_name="personnelprofile",
            new_name="app_personn_distrib_750d99_idx",
            old_name="personnel_p_distrib_d9d60c_idx",
        ),
        migrations.RenameIndex(
            model_name="personnelprofile",
            new_name="app_personn_area_id_a350b9_idx",
            old_name="personnel_p_area_id_badd5a_idx",
        ),
        migrations.AlterModelTable(
            name="area",
            table="app_personnel_area",
        ),
        migrations.AlterModelTable(
            name="certification",
            table="app_personnel_certification",
        ),
        migrations.AlterModelTable(
            name="certificationtype",
            table="app_personnel_certification_type",
        ),
        migrations.AlterModelTable(
            name="department",
            table="app_personnel_department",
        ),
        migrations.AlterModelTable(
            name="emergencycontact",
            table="app_personnel_emergency_contact",
        ),
        migrations.AlterModelTable(
            name="medicalrecord",
            table="app_personnel_medical_record",
        ),
        migrations.AlterModelTable(
            name="performancemetric",
            table="app_personnel_performance_metric",
        ),
        migrations.AlterModelTable(
            name="personnelprofile",
            table="app_personnel_profile",
        ),
    ]
