# Generated by Django 5.0.6 on 2025-12-30 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0005_countrymodel_distributorcenter_country_and_more"),
        (
            "personnel",
            "0002_rename_personnel_c_personn_aac960_idx_app_personn_personn_d82057_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="personnelprofile",
            name="app_personn_distrib_750d99_idx",
        ),
        migrations.RemoveField(
            model_name="personnelprofile",
            name="distributor_center",
        ),
        migrations.AddField(
            model_name="personnelprofile",
            name="distributor_centers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Todos los centros de distribución donde puede trabajar el empleado",
                related_name="all_personnel",
                to="maintenance.distributorcenter",
                verbose_name="Centros de distribución",
            ),
        ),
        migrations.AddField(
            model_name="personnelprofile",
            name="primary_distributor_center",
            field=models.ForeignKey(
                blank=True,
                db_column="distributor_center_id",
                help_text="Centro de distribución principal al que pertenece el empleado",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_personnel",
                to="maintenance.distributorcenter",
                verbose_name="Centro de distribución principal",
            ),
        ),
        migrations.AddIndex(
            model_name="personnelprofile",
            index=models.Index(
                fields=["primary_distributor_center", "is_active"],
                name="app_personn_distrib_750d99_idx",
            ),
        ),
    ]
