# Generated by Django 5.0.6 on 2025-12-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personnel",
            "0003_remove_personnelprofile_app_personn_distrib_750d99_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Foto del empleado (formato: JPG, PNG, máx 5MB)",
                null=True,
                upload_to="personnel/photos/%Y/%m/",
                verbose_name="Foto de perfil",
            ),
        ),
    ]
