# Generated by Django 4.2.19 on 2026-01-03 05:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personnel", "0004_personnelprofile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceMetricType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: Productividad, Pallets movidos, Calidad, etc.",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la métrica",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único para identificar la métrica (snake_case)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de qué mide esta métrica",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("NUMERIC", "Numérico"),
                            ("RATING", "Calificación (1-5)"),
                            ("PERCENTAGE", "Porcentaje (0-100)"),
                            ("BOOLEAN", "Sí/No"),
                            ("TEXT", "Texto"),
                        ],
                        default="NUMERIC",
                        max_length=20,
                        verbose_name="Tipo de métrica",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Ej: pallets, horas, %, etc.",
                        max_length=50,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor mínimo permitido (opcional)",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor mínimo",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor máximo permitido (opcional)",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor máximo",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=10,
                        help_text="Peso de esta métrica en el cálculo del score general (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Peso",
                    ),
                ),
                (
                    "applicable_position_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de position_type donde aplica esta métrica",
                        verbose_name="Tipos de posición aplicables",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Si esta métrica es obligatoria en la evaluación",
                        verbose_name="Es requerida",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activa"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden en que se muestra en el formulario",
                        verbose_name="Orden de visualización",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Instrucciones para el evaluador",
                        verbose_name="Texto de ayuda",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metric_types_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Métrica de Desempeño",
                "verbose_name_plural": "Tipos de Métricas de Desempeño",
                "db_table": "app_personnel_metric_type",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_date",
                    models.DateField(db_index=True, verbose_name="Fecha de evaluación"),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                            ("QUARTERLY", "Trimestral"),
                            ("ANNUAL", "Anual"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="Período",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculado automáticamente basado en las métricas (0-5)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Puntuación general",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="Comentarios generales"),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=True,
                        help_text="Evaluación aún no finalizada",
                        verbose_name="Es borrador",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuando se finalizó la evaluación",
                        null=True,
                        verbose_name="Fecha de envío",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_conducted",
                        to="personnel.personnelprofile",
                        verbose_name="Evaluado por",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="personnel.personnelprofile",
                        verbose_name="Personal evaluado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Desempeño",
                "verbose_name_plural": "Evaluaciones de Desempeño",
                "db_table": "app_personnel_evaluation",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationMetricValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numeric_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor numérico",
                    ),
                ),
                (
                    "text_value",
                    models.TextField(blank=True, verbose_name="Valor de texto"),
                ),
                (
                    "boolean_value",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Valor booleano"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Comentarios")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_values",
                        to="personnel.performanceevaluation",
                        verbose_name="Evaluación",
                    ),
                ),
                (
                    "metric_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="personnel.performancemetrictype",
                        verbose_name="Tipo de métrica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de Métrica",
                "verbose_name_plural": "Valores de Métricas",
                "db_table": "app_personnel_evaluation_metric_value",
            },
        ),
        migrations.AddIndex(
            model_name="performancemetrictype",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="app_personn_is_acti_e52d66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performanceevaluation",
            index=models.Index(
                fields=["personnel", "-evaluation_date"],
                name="app_personn_personn_bf0713_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performanceevaluation",
            index=models.Index(
                fields=["period", "-evaluation_date"],
                name="app_personn_period_407fb0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="performanceevaluation",
            index=models.Index(
                fields=["is_draft"], name="app_personn_is_draf_56d628_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluationmetricvalue",
            unique_together={("evaluation", "metric_type")},
        ),
    ]
