# Generated by Django 5.0.6 on 2026-01-07 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0005_performancemetrictype_performanceevaluation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Se genera automáticamente si no se proporciona",
                max_length=50,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Código",
            ),
        ),
    ]
