# Generated by Django 5.0.6 on 2026-01-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0007_alter_department_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="department",
            unique_together=set(),
        ),
    ]
