# Generated by Django 5.0.6 on 2026-01-07 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0008_alter_department_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnelprofile",
            name="address",
            field=models.TextField(blank=True, verbose_name="Dirección residencial"),
        ),
        migrations.AlterField(
            model_name="personnelprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
        ),
        migrations.AlterField(
            model_name="personnelprofile",
            name="personal_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(13)],
                verbose_name="Número de identidad",
            ),
        ),
    ]
