# Generated by Django 5.0.6 on 2026-03-03 03:19

import apps.personnel.models.certification
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0009_make_personal_fields_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de completado"
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certifications_completed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Completado por",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="completion_notes",
            field=models.TextField(blank=True, verbose_name="Notas de completado"),
        ),
        migrations.AddField(
            model_name="certification",
            name="non_completion_reason",
            field=models.TextField(blank=True, verbose_name="Motivo de no completado"),
        ),
        migrations.AddField(
            model_name="certification",
            name="signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.personnel.models.certification.certification_signature_path,
                verbose_name="Firma del participante",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("IN_PROGRESS", "En Progreso"),
                    ("COMPLETED", "Completado"),
                    ("NOT_COMPLETED", "No Completó"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
