# Generated by Django 4.2.19 on 2026-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_make_fields_optional_for_bulk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelprofile',
            name='position_type',
            field=models.CharField(choices=[('PICKER', 'Picker'), ('COUNTER', 'Contador'), ('OPM', 'Operador de Montacargas'), ('YARD_DRIVER', 'Conductor de Patio'), ('LOADER', 'Cargador'), ('WAREHOUSE_ASSISTANT', 'Ayudante de Almacén'), ('SECURITY_GUARD', 'Guardia de Seguridad'), ('DELIVERY_DRIVER', 'Conductor de Delivery'), ('ADMINISTRATIVE', 'Administrativo'), ('OTHER', 'Otro')], db_index=True, help_text='Categoría general del puesto', max_length=30, verbose_name='Tipo de posición'),
        ),
        migrations.AddIndex(
            model_name='personnelprofile',
            index=models.Index(fields=['position_type', 'is_active'], name='app_personn_positio_07cf24_idx'),
        ),
        migrations.AddIndex(
            model_name='personnelprofile',
            index=models.Index(fields=['first_name', 'last_name'], name='app_personn_first_n_14309b_idx'),
        ),
    ]
