# Generated by Django 4.2.16 on 2026-04-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_personnelmetricsample'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='personnelmetricsample',
            new_name='app_personn_personn_95a825_idx',
            old_name='metric_sample_person_idx',
        ),
        migrations.RenameIndex(
            model_name='personnelmetricsample',
            new_name='app_personn_metric__03c4fe_idx',
            old_name='metric_sample_type_idx',
        ),
        migrations.RenameIndex(
            model_name='personnelmetricsample',
            new_name='app_personn_operati_7061be_idx',
            old_name='metric_sample_date_idx',
        ),
        migrations.RenameIndex(
            model_name='personnelmetricsample',
            new_name='app_personn_pauta_i_e2a02a_idx',
            old_name='metric_sample_pauta_idx',
        ),
        migrations.AlterField(
            model_name='personnelmetricsample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
