version: '3.3'
services:
  db:
    container_name: reimpress-mssql
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
        - ${DB_PORT}:1433
    user: root
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    restart: always
    volumes:
        - ./data:/var/opt/mssql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db