# Generated by Django 3.2.20 on 2023-09-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDetailOutputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('created_at_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Hora de Creación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('detail_required', models.BooleanField(default=False, verbose_name='Requiere detalles')),
            ],
            options={
                'verbose_name': 'Tipo de salida de producto',
                'verbose_name_plural': 'Tipos de salida de producto',
                'db_table': 'type_detail_output',
            },
        ),
    ]
