# Generated by Django 3.2.20 on 2023-09-25 19:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Detalle de tracker',
                'verbose_name_plural': 'Detalles de tracker',
                'db_table': 'tracker_detail',
            },
        ),
        migrations.CreateModel(
            name='TrackerDetailOutputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('expiration_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de vencimiento')),
            ],
            options={
                'verbose_name': 'Detalle de salida de tracker',
                'verbose_name_plural': 'Detalles de salida de tracker',
                'db_table': 'tracker_detail_output',
            },
        ),
        migrations.CreateModel(
            name='TrackerDetailProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Detalle de producto de tracker',
                'verbose_name_plural': 'Detalles de producto de tracker',
                'db_table': 'tracker_detail_product',
            },
        ),
        migrations.CreateModel(
            name='TypeDetailOutputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('detail_required', models.BooleanField(default=False, verbose_name='Requiere detalles')),
            ],
            options={
                'verbose_name': 'Tipo de salida de producto',
                'verbose_name_plural': 'Tipos de salida de producto',
                'db_table': 'type_detail_output',
            },
        ),
        migrations.CreateModel(
            name='TrackerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de placa')),
                ('input_document_number', models.CharField(error_messages={'unique': 'El numero de documento de entrada ya existe, debe ser unico'}, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El numero de documento de entrada debe ser un numero', regex='^[0-9]+$')], verbose_name='Número de documento de entrada')),
                ('output_document_number', models.CharField(error_messages={'unique': 'El numero de documento de salida ya existe, debe ser unico'}, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El numero de documento de salida debe ser un numero', regex='^[0-9]+$')], verbose_name='Número de documento de salida')),
                ('transfer_number', models.CharField(error_messages={'unique': 'El numero de traslado 5001 ya existe, debe ser unico'}, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El numero de traslado debe ser un numero', regex='^[0-9]+$')], verbose_name='Número de traslado')),
                ('accounted', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El numero de traslado debe ser un numero', regex='^[0-9]+$')], verbose_name='Contabilizado')),
                ('input_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrada')),
                ('output_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('time_invested', models.IntegerField(blank=True, null=True, verbose_name='Tiempo invertido')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('EDITED', 'EDITED')], default='PENDING', max_length=50, verbose_name='Estado')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_destination_location', to='maintenance.locationmodel', verbose_name='Localidad de destino')),
                ('distributor_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_distributor_center', to='maintenance.distributorcenter', verbose_name='Centro de distribución')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_driver', to='maintenance.drivermodel', verbose_name='Conductor')),
                ('operator_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_operator_1', to='maintenance.operatormodel', verbose_name='Operador 1')),
                ('operator_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_operator_2', to='maintenance.operatormodel', verbose_name='Operador 2')),
                ('origin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_origin_location', to='maintenance.locationmodel', verbose_name='Localidad de origen')),
                ('output_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_output_type', to='maintenance.outputtypemodel', verbose_name='Tipo de salida')),
                ('trailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_trailer', to='maintenance.trailermodel', verbose_name='Trailer')),
                ('transporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_transporter', to='maintenance.transportermodel', verbose_name='Transportista')),
            ],
            options={
                'verbose_name': 'Tracker',
                'verbose_name_plural': 'Trackers',
                'db_table': 'tracker',
            },
        ),
    ]
