# Generated by Django 3.2.20 on 2023-09-20 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='trackerdetailproductmodel',
            name='tracker_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_product_detail', to='tracker.trackerdetailmodel', verbose_name='Tracker detalle'),
        ),
        migrations.AddField(
            model_name='trackerdetailoutputmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_detail_output_product', to='maintenance.productmodel', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='trackerdetailoutputmodel',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_detail_output', to='tracker.trackermodel', verbose_name='Tracker'),
        ),
        migrations.AddField(
            model_name='trackerdetailmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_detail_product', to='maintenance.productmodel', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='trackerdetailmodel',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_detail', to='tracker.trackermodel', verbose_name='Tracker'),
        ),
        migrations.AlterUniqueTogether(
            name='trackerdetailoutputmodel',
            unique_together={('tracker', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='trackerdetailmodel',
            unique_together={('tracker', 'product')},
        ),
    ]
