# Generated by Django 3.2.20 on 2023-09-12 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_trackerdetailmodel_trackermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackermodel',
            name='input_document_number',
            field=models.CharField(error_messages={'unique': 'El numero de documento de entrada ya existe, debe ser unico'}, max_length=50, null=True, unique=True, verbose_name='Número de documento de entrada'),
        ),
        migrations.AlterField(
            model_name='trackermodel',
            name='output_document_number',
            field=models.CharField(error_messages={'unique': 'El numero de documento de salida ya existe, debe ser unico'}, max_length=50, null=True, unique=True, verbose_name='Número de documento de salida'),
        ),
        migrations.AlterField(
            model_name='trackermodel',
            name='transfer_number',
            field=models.CharField(error_messages={'unique': 'El numero de traslado 5001 ya existe, debe ser unico'}, max_length=50, null=True, unique=True, verbose_name='Número de traslado'),
        ),
        migrations.AlterField(
            model_name='trackermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
