# Generated by Django 3.2.20 on 2023-09-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackermodel',
            name='type',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('IMPORT', 'IMPORT')], default='LOCAL', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='trackermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('EDITED', 'EDITED')], default='EDITED', max_length=50, verbose_name='Estado'),
        ),
    ]
