# Generated by Django 3.2.20 on 2023-09-23 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_trackerdetailoutputmodel_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdetailoutputmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de vencimiento'),
        ),
    ]
