# Generated by Django 3.2.20 on 2023-09-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_outputtypemodel'),
        ('tracker', '0003_auto_20230911_2004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackerdetailmodel',
            unique_together={('tracker', 'product')},
        ),
        migrations.CreateModel(
            name='TrackerDetailProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('created_at_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Hora de Creación')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('tracker_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_product_detail', to='tracker.trackerdetailmodel', verbose_name='Tracker detalle')),
            ],
            options={
                'verbose_name': 'Detalle de producto de tracker',
                'verbose_name_plural': 'Detalles de producto de tracker',
                'db_table': 'tracker_detail_product',
            },
        ),
    ]
