# Generated by Django 3.2.20 on 2023-09-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20230925_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackermodel',
            name='container_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de contenedor'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='invoice_number',
            field=models.CharField(blank=True, error_messages={'unique': 'El numero de factura ya existe, debe ser unico'}, max_length=50, null=True, unique=True, verbose_name='Número de factura'),
        ),
    ]
