# Generated by Django 3.2.20 on 2023-09-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20230912_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdetailproductmodel',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
