# Generated by Django 3.2.20 on 2023-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20230925_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackermodel',
            name='driver_import',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conductor importados'),
        ),
    ]
