# Generated by Django 3.2.20 on 2023-10-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_productmodel_cost'),
        ('tracker', '0005_trackermodel_driver_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdetailmodel',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_detail', to='tracker.trackermodel', verbose_name='Tracker'),
        ),
        migrations.AlterField(
            model_name='trackerdetailoutputmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_detail_output_product', to='maintenance.productmodel', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='trackerdetailoutputmodel',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_detail_output', to='tracker.trackermodel', verbose_name='Tracker'),
        ),
        migrations.AlterField(
            model_name='trackerdetailproductmodel',
            name='tracker_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_product_detail', to='tracker.trackerdetailmodel', verbose_name='Tracker detalle'),
        ),
    ]
