# Generated by Django 3.2.20 on 2023-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_trackerdetailproductmodel_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerdetailmodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='trackerdetailmodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='trackerdetailproductmodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='trackerdetailproductmodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='trackermodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='trackermodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='typedetailoutputmodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='typedetailoutputmodel',
            name='created_at_time',
        ),
        migrations.AddField(
            model_name='trackerdetailmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='trackerdetailproductmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='typedetailoutputmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
    ]
