# Generated by Django 3.2.20 on 2023-09-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20230912_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdetailmodel',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_detail', to='tracker.trackermodel', verbose_name='Tracker'),
        ),
    ]
