# Generated by Django 3.2.20 on 2023-10-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20231003_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackermodel',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de factura'),
        ),
    ]
