# Generated by Django 3.2.20 on 2023-10-06 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_trackermodel_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdetailoutputmodel',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
