# Generated by Django 3.2.20 on 2023-09-14 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_trackerdetailmodel_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackermodel',
            name='accounted',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El numero de traslado debe ser un numero', regex='^[0-9]+$')], verbose_name='Contabilizado'),
        ),
        migrations.AlterField(
            model_name='trackermodel',
            name='input_document_number',
            field=models.CharField(error_messages={'unique': 'El numero de documento de entrada ya existe, debe ser unico'}, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El numero de documento de entrada debe ser un numero', regex='^[0-9]+$')], verbose_name='Número de documento de entrada'),
        ),
        migrations.AlterField(
            model_name='trackermodel',
            name='output_document_number',
            field=models.CharField(error_messages={'unique': 'El numero de documento de salida ya existe, debe ser unico'}, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El numero de documento de salida debe ser un numero', regex='^[0-9]+$')], verbose_name='Número de documento de salida'),
        ),
        migrations.AlterField(
            model_name='trackermodel',
            name='transfer_number',
            field=models.CharField(error_messages={'unique': 'El numero de traslado 5001 ya existe, debe ser unico'}, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El numero de traslado debe ser un numero', regex='^[0-9]+$')], verbose_name='Número de traslado'),
        ),
    ]
