# Generated by Django 3.2.20 on 2023-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_trackerdetailoutputmodel_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackermodel',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observacion'),
        ),
    ]
