# Generated by Django 3.2.20 on 2023-09-15 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_remove_trailermodel_transporter'),
        ('tracker', '0008_auto_20230914_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerDetailOutputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_detail_output_product', to='maintenance.productmodel', verbose_name='Producto')),
                ('tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_detail_output', to='tracker.trackermodel', verbose_name='Tracker')),
            ],
            options={
                'verbose_name': 'Detalle de salida de tracker',
                'verbose_name_plural': 'Detalles de salida de tracker',
                'db_table': 'tracker_detail_output',
                'unique_together': {('tracker', 'product')},
            },
        ),
    ]
