# Generated by Django 3.2.20 on 2023-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_trackerdetailoutputmodel_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackermodel',
            name='archivo',
            field=models.BinaryField(blank=True, null=True, verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='archivo_name',
            field=models.TextField(blank=True, null=True, verbose_name='Nombre del Archivo'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observacion'),
        ),
    ]
