# Generated by Django 3.2.20 on 2023-11-07 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_trackermodel_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackermodel',
            name='transfer_number',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El numero de traslado debe ser un numero', regex='^[0-9]+$')], verbose_name='Número de traslado'),
        ),
    ]
