# Generated by Django 3.2.20 on 2023-09-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_trackerdetailoutputmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackermodel',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado'),
        ),
    ]
