# Generated by Django 3.2.20 on 2024-02-08 05:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20240208_0556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20240208_0556'),
        ('tracker', '0010_alter_trackermodel_transfer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputDetailT2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('CHECKED', 'CHECKED'), ('REJECTED', 'REJECTED'), ('AUTHORIZED', 'AUTHORIZED'), ('APPLIED', 'APPLIED')], default='CREATED', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Detalle de salida T2',
                'verbose_name_plural': 'Detalles de salida T2',
                'db_table': 'output_detail_t2',
            },
        ),
        migrations.AddField(
            model_name='trackerdetailoutputmodel',
            name='tracker_detail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_detail_output_tracker_detail_product', to='tracker.trackerdetailproductmodel', verbose_name='Tracker detail product'),
        ),
        migrations.AddField(
            model_name='trackerdetailproductmodel',
            name='available_quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad disponible'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='archivo',
            field=models.BinaryField(blank=True, null=True, verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='archivo_name',
            field=models.TextField(blank=True, null=True, verbose_name='Nombre del Archivo'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_order', to='order.ordermodel', verbose_name='Pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='trackerdetailoutputmodel',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TrackerOutputT2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote_output_t2', to='maintenance.lotmodel', verbose_name='Lote')),
                ('output_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_detail_tracker_t2', to='tracker.outputdetailt2model', verbose_name='Salida')),
                ('tracker_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_detail_output_t2', to='tracker.trackerdetailproductmodel', verbose_name='Tracker')),
            ],
            options={
                'verbose_name': 'Tracker de salida T2',
                'verbose_name_plural': 'Trackers de salida T2',
                'db_table': 'tracker_output_t2',
            },
        ),
        migrations.CreateModel(
            name='OutputT2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('CHECKED', 'CHECKED'), ('REJECTED', 'REJECTED'), ('AUTHORIZED', 'AUTHORIZED'), ('APPLIED', 'APPLIED')], default='CREATED', max_length=10, verbose_name='Estado')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('simulation', models.JSONField(blank=True, null=True, verbose_name='simulación')),
                ('pre_sale_date', models.DateField(default=datetime.datetime(2024, 2, 8, 5, 56, 22, 998236), verbose_name='Fecha de preventa')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_center_output_t2', to='maintenance.distributorcenter', verbose_name='Centro de distribución')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_output_t2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('user_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver_output_t2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario receptor')),
                ('user_authorizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_authorizer_output_t2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario autorizador')),
                ('user_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_check_output_t2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario check')),
            ],
            options={
                'verbose_name': 'Salida T2',
                'verbose_name_plural': 'Salidas T2',
                'db_table': 'output_t2',
            },
        ),
        migrations.AddField(
            model_name='outputdetailt2model',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_detail_t2', to='tracker.outputt2model', verbose_name='Salida'),
        ),
        migrations.AddField(
            model_name='outputdetailt2model',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_output_detail_t2', to='maintenance.productmodel', verbose_name='Producto'),
        ),
    ]
