# Generated by Django 3.2.20 on 2023-11-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20231117_1738'),
        ('tracker', '0010_alter_trackermodel_transfer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerdetailoutputmodel',
            name='tracker_detail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_detail_output_tracker_detail_product', to='tracker.trackerdetailproductmodel', verbose_name='Tracker detail product'),
        ),
        migrations.AddField(
            model_name='trackerdetailproductmodel',
            name='available_quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad disponible'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='archivo',
            field=models.BinaryField(blank=True, null=True, verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='archivo_name',
            field=models.TextField(blank=True, null=True, verbose_name='Nombre del Archivo'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_order', to='order.ordermodel', verbose_name='Pedido'),
        ),
    ]
