# Generated by Django 3.2.20 on 2024-04-25 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20240208_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputt2model',
            name='pre_sale_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 25, 8, 23, 50, 65295), verbose_name='Fecha de preventa'),
        ),
    ]
