# Generated by Django 3.2.20 on 2023-11-20 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20231117_1738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackerdetailoutputmodel',
            unique_together=set(),
        ),
    ]
