# Generated by Django 3.2.20 on 2024-04-25 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_outputt2model_pre_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackermodel',
            name='exclude_tat',
            field=models.BooleanField(default=False, verbose_name='Excluir del TAT'),
        ),
        migrations.AlterField(
            model_name='outputt2model',
            name='pre_sale_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 25, 11, 52, 23, 790284), verbose_name='Fecha de preventa'),
        ),
    ]
