# Generated by Django 3.2.20 on 2023-12-02 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0004_auto_20231117_1738'),
        ('tracker', '0012_alter_trackerdetailoutputmodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputT2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('CHECKED', 'CHECKED'), ('APPLIED', 'APPLIED')], default='CREATED', max_length=10, verbose_name='Estado')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_center_output_t2', to='maintenance.distributorcenter', verbose_name='Centro de distribución')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_output_t2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('user_authorizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_authorizer_output_t2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario autorizador')),
                ('user_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver_output_t2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario receptor')),
            ],
            options={
                'verbose_name': 'Salida T2',
                'verbose_name_plural': 'Salidas T2',
                'db_table': 'output_t2',
            },
        ),
        migrations.CreateModel(
            name='TrackerOutputT2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_output_t2', to='tracker.outputt2model', verbose_name='Salida')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_output_t2', to='tracker.trackerdetailproductmodel', verbose_name='Tracker')),
            ],
            options={
                'verbose_name': 'Tracker de salida T2',
                'verbose_name_plural': 'Trackers de salida T2',
                'db_table': 'tracker_output_t2',
            },
        ),
        migrations.CreateModel(
            name='OutputDetailT2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('CHECKED', 'CHECKED'), ('REJECTED', 'REJECTED'), ('AUTHORIZED', 'AUTHORIZED'), ('APPLIED', 'APPLIED')], default='CREATED', max_length=10, verbose_name='Estado')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_detail_t2', to='tracker.outputt2model', verbose_name='Salida')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_output_detail_t2', to='maintenance.productmodel', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de salida T2',
                'verbose_name_plural': 'Detalles de salida T2',
                'db_table': 'output_detail_t2',
            },
        ),
    ]
