# Generated by Django 5.2 on 2025-04-16 02:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('tracker', '0013_auto_20240425_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackermodel',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='trackermodel',
            name='archivo_name',
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='file_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_file_1', to='document.documentmodel', verbose_name='Archivo 1'),
        ),
        migrations.AddField(
            model_name='trackermodel',
            name='file_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_file_2', to='document.documentmodel', verbose_name='Archivo 2'),
        ),
        migrations.AlterField(
            model_name='outputt2model',
            name='pre_sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de preventa'),
        ),
    ]
