# Generated by Django 3.2.20 on 2025-03-03 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20240425_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputt2model',
            name='pre_sale_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 3, 22, 52, 54, 932680), verbose_name='Fecha de preventa'),
        ),
    ]
