# Generated by Django 3.2.20 on 2023-12-08 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_lotmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0013_outputdetailt2model_outputt2model_trackeroutputt2model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputt2model',
            old_name='user_receiver',
            new_name='user_applied',
        ),
        migrations.RemoveField(
            model_name='trackeroutputt2model',
            name='output',
        ),
        migrations.RemoveField(
            model_name='trackeroutputt2model',
            name='tracker',
        ),
        migrations.AddField(
            model_name='outputt2model',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualización'),
        ),
        migrations.AddField(
            model_name='outputt2model',
            name='user_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_check_output_t2', to=settings.AUTH_USER_MODEL, verbose_name='Usuario check'),
        ),
        migrations.AddField(
            model_name='trackeroutputt2model',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote_output_t2', to='maintenance.lotmodel', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='trackeroutputt2model',
            name='output_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_detail_tracker_t2', to='tracker.outputdetailt2model', verbose_name='Salida'),
        ),
        migrations.AddField(
            model_name='trackeroutputt2model',
            name='tracker_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_detail_output_t2', to='tracker.trackerdetailproductmodel', verbose_name='Tracker'),
        ),
        migrations.AlterField(
            model_name='outputt2model',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('CHECKED', 'CHECKED'), ('REJECTED', 'REJECTED'), ('AUTHORIZED', 'AUTHORIZED'), ('APPLIED', 'APPLIED')], default='CREATED', max_length=10, verbose_name='Estado'),
        ),
    ]
