# Generated by Django 3.2.20 on 2023-12-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20231208_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputdetailt2model',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='trackeroutputt2model',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
