# Generated by Django 3.2.20 on 2025-03-03 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_outputt2model_pre_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputt2model',
            name='pre_sale_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 3, 22, 59, 58, 620605), verbose_name='Fecha de preventa'),
        ),
    ]
