# Generated by Django 3.2.20 on 2024-01-06 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20231217_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputt2model',
            name='pre_sale_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 6, 15, 22, 57, 457770), verbose_name='Fecha de preventa'),
        ),
        migrations.AddField(
            model_name='outputt2model',
            name='simulation',
            field=models.JSONField(blank=True, null=True, verbose_name='simulación'),
        ),
    ]
