# Generated by Django 3.2.20 on 2024-04-24 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20240106_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputt2model',
            name='pre_sale_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de preventa'),
        ),
    ]
