# Generated by Django 4.2.19 on 2025-03-19 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0020_alter_outputt2model_pre_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outputt2model",
            name="pre_sale_date",
            field=models.DateField(
                default=datetime.datetime(2025, 3, 19, 10, 33, 31, 354597),
                verbose_name="Fecha de preventa",
            ),
        ),
    ]
