# Generated by Django 4.2.19 on 2025-03-30 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0021_alter_outputt2model_pre_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outputt2model",
            name="pre_sale_date",
            field=models.DateField(
                default=datetime.datetime(2025, 3, 30, 7, 57, 54, 95865),
                verbose_name="Fecha de preventa",
            ),
        ),
    ]
