# Generated by Django 4.2.19 on 2025-03-31 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0022_alter_outputt2model_pre_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outputt2model",
            name="pre_sale_date",
            field=models.DateField(
                default=datetime.datetime(2025, 3, 31, 22, 40, 38, 356282),
                verbose_name="Fecha de preventa",
            ),
        ),
    ]
