# Generated by Django 4.2.19 on 2025-04-01 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0023_alter_outputt2model_pre_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outputt2model",
            name="pre_sale_date",
            field=models.DateField(
                default=datetime.datetime(2025, 4, 1, 1, 12, 11, 638254),
                verbose_name="Fecha de preventa",
            ),
        ),
    ]
