# Generated by Django 4.2.19 on 2025-04-01 01:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_documentmodel_folder_documentmodel_subfolder_and_more"),
        ("tracker", "0024_alter_outputt2model_pre_sale_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackermodel",
            name="archivo",
        ),
        migrations.RemoveField(
            model_name="trackermodel",
            name="archivo_name",
        ),
        migrations.AddField(
            model_name="trackermodel",
            name="file_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracker_file_1",
                to="document.documentmodel",
                verbose_name="Archivo 1",
            ),
        ),
        migrations.AddField(
            model_name="trackermodel",
            name="file_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracker_file_2",
                to="document.documentmodel",
                verbose_name="Archivo 2",
            ),
        ),
        migrations.AlterField(
            model_name="outputt2model",
            name="pre_sale_date",
            field=models.DateField(
                default=datetime.datetime(2025, 4, 1, 1, 54, 31, 650503),
                verbose_name="Fecha de preventa",
            ),
        ),
    ]
