# Generated by Django 4.2.19 on 2025-04-04 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0025_remove_trackermodel_archivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outputt2model",
            name="pre_sale_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de preventa"
            ),
        ),
    ]
