# Generated by Django 3.2.20 on 2023-09-05 03:26

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiered_access', models.BooleanField(default=False, help_text='requiere que se le asigne el acceso a los usuarios', verbose_name='requiere access')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_group', to='auth.group', verbose_name='group')),
            ],
            options={
                'db_table': 'auth_group_detail',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(error_messages={'max_length': 'El nombre debe tener menos de 60 caracteres', 'required': 'El nombre es es obligatorio'}, max_length=60, verbose_name='first name')),
                ('last_name', models.CharField(error_messages={'max_length': 'El apellido debe tener menos de 60 caracteres', 'required': 'El apellido es obligatorio'}, max_length=60, verbose_name='last name')),
                ('email', models.EmailField(error_messages={'required': 'El email es obligatorio', 'unique': 'El email ya existe'}, max_length=254, unique=True, verbose_name='email address')),
                ('codigo_empleado', models.IntegerField(blank=True, error_messages={'unique': 'El numero de empleado ya existe, debe ser unico'}, null=True, unique=True, verbose_name='numero de empleado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centro_distribucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_centro_distribucion', to='maintenance.distributorcenter', verbose_name='centro de distribución')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
