# Generated by Django 3.2.20 on 2024-02-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20240208_0556'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='distributor_centers',
            field=models.ManyToManyField(blank=True, related_name='user_distributor_centers', to='maintenance.DistributorCenter', verbose_name='centros de distribución'),
        ),
    ]
