# Generated by Django 3.2.20 on 2024-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_lotmodel'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='distributions_centers',
            field=models.ManyToManyField(blank=True, related_name='user_distributions_centers', to='maintenance.DistributorCenter', verbose_name='centros de distribucion'),
        ),
    ]
