# Generated by Django 3.2.20 on 2023-08-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('maintenance', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailgroup',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_group', to='auth.group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='centro_distribucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_centro_distribucion', to='maintenance.centrodistribucion', verbose_name='centro de distribución'),
        ),
    ]
