# Generated by Django 3.2.20 on 2023-09-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='codigo_empleado',
            new_name='employee_number',
        ),
    ]
