# Generated by Django 3.2.20 on 2024-04-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20240208_0556'),
        ('user', '0002_usermodel_distributor_centers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='distributor_centers',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='distributions_centers',
            field=models.ManyToManyField(blank=True, related_name='user_distributions_centers', to='maintenance.DistributorCenter', verbose_name='centros de distribucion'),
        ),
    ]
