# Generated by Django 5.2 on 2025-04-16 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240425_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('type', models.CharField(choices=[('UBICACION', 'Location'), ('ALERTA', 'Alert'), ('RECORDATORIO', 'Reminder'), ('TAREA', 'Task'), ('ACTUALIZACION', 'Update'), ('ADVERTENCIA', 'Warning'), ('INFORMACION', 'Info'), ('ERROR', 'Error'), ('REGISTRO', 'Registration'), ('APROBACION', 'Aproval'), ('CONFIRMACION', 'Confirmation'), ('RECHAZO', 'Rejection'), ('RECLAMO', 'Claim')], max_length=75)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=150, null=True)),
                ('description', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('identifier', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=150, null=True)),
                ('module', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('RECLAMO', 'Claim'), ('TRACKER', 'Tracker'), ('USUARIO', 'User'), ('PRODUCTO', 'Product'), ('OTROS', 'Others')], max_length=75)),
                ('json', models.JSONField(null=True)),
                ('html', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
