# Generated by Django 4.2.19 on 2025-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_notificationmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmodel",
            name="module",
            field=models.CharField(
                choices=[
                    ("T1", "T1"),
                    ("T2", "T2"),
                    ("RECLAMO", "Claim"),
                    ("TRACKER", "Tracker"),
                    ("USUARIO", "User"),
                    ("PRODUCTO", "Product"),
                    ("OTROS", "Others"),
                ],
                max_length=75,
            ),
        ),
        migrations.AlterField(
            model_name="notificationmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("UBICACION", "Location"),
                    ("ALERTA", "Alert"),
                    ("RECORDATORIO", "Reminder"),
                    ("TAREA", "Task"),
                    ("ACTUALIZACION", "Update"),
                    ("ADVERTENCIA", "Warning"),
                    ("INFORMACION", "Info"),
                    ("ERROR", "Error"),
                    ("REGISTRO", "Registration"),
                    ("APROBACION", "Aproval"),
                    ("CONFIRMACION", "Confirmation"),
                    ("RECHAZO", "Rejection"),
                ],
                max_length=75,
            ),
        ),
    ]
