# Generated by Django 5.0.6 on 2026-01-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmodel",
            name="module",
            field=models.CharField(
                choices=[
                    ("T1", "T1"),
                    ("T2", "T2"),
                    ("RECLAMO", "Claim"),
                    ("TRACKER", "Tracker"),
                    ("USUARIO", "User"),
                    ("PRODUCTO", "Product"),
                    ("TOKENS", "Tokens"),
                    ("OTROS", "Others"),
                ],
                max_length=75,
            ),
        ),
    ]
