version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    env_file:
      - ../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    networks:
      - dokploy-network
    restart: unless-stopped

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - dokploy-network

  celery-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: ["/entrypoint-celery.sh"]
    command: celery -A config worker -l info
    env_file:
      - ../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - web
    networks:
      - dokploy-network
    restart: unless-stopped

  celery-beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: ["/entrypoint-celery.sh"]
    command: celery -A config beat -l info
    env_file:
      - ../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - web
    networks:
      - dokploy-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  dokploy-network:
    external: true