# Generated by Django 4.2.19 on 2026-01-09 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0005_countrymodel_distributorcenter_country_and_more"),
        ("personnel", "0009_make_personal_fields_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExitPassDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "destination",
                    models.CharField(max_length=255, verbose_name="Destino"),
                ),
                ("purpose", models.TextField(verbose_name="Propósito/Motivo")),
                (
                    "vehicle_plate",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Placa del Vehículo"
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre del Conductor"
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Esperada de Retorno"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pase de Salida",
                "verbose_name_plural": "Detalles de Pases de Salida",
                "db_table": "token_exit_pass_detail",
            },
        ),
        migrations.CreateModel(
            name="TokenRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "token_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Código UUID",
                    ),
                ),
                (
                    "display_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Token",
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("PERMIT_HOUR", "Permiso por Hora"),
                            ("PERMIT_DAY", "Permiso por Día"),
                            ("EXIT_PASS", "Pase de Salida"),
                            ("SUBSTITUTION", "Sustitución"),
                            ("RATE_CHANGE", "Cambio de Tasa"),
                            ("OVERTIME", "Horas Extra"),
                            ("SHIFT_CHANGE", "Cambio de Turno"),
                            ("UNIFORM_DELIVERY", "Entrega de Uniforme"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PENDING_L1", "Pendiente Nivel 1"),
                            ("PENDING_L2", "Pendiente Nivel 2"),
                            ("PENDING_L3", "Pendiente Nivel 3"),
                            ("APPROVED", "Aprobado"),
                            ("USED", "Utilizado"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELLED", "Cancelado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "qr_code_url",
                    models.URLField(blank=True, null=True, verbose_name="URL del QR"),
                ),
                (
                    "requires_level_1",
                    models.BooleanField(default=True, verbose_name="Requiere Nivel 1"),
                ),
                (
                    "requires_level_2",
                    models.BooleanField(default=True, verbose_name="Requiere Nivel 2"),
                ),
                (
                    "requires_level_3",
                    models.BooleanField(default=False, verbose_name="Requiere Nivel 3"),
                ),
                (
                    "approved_level_1_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación L1"
                    ),
                ),
                (
                    "approved_level_1_notes",
                    models.TextField(blank=True, verbose_name="Notas Aprobación L1"),
                ),
                (
                    "approved_level_2_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación L2"
                    ),
                ),
                (
                    "approved_level_2_notes",
                    models.TextField(blank=True, verbose_name="Notas Aprobación L2"),
                ),
                (
                    "approved_level_3_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación L3"
                    ),
                ),
                (
                    "approved_level_3_notes",
                    models.TextField(blank=True, verbose_name="Notas Aprobación L3"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Rechazo"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo de Rechazo"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Validación"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Válido Desde")),
                ("valid_until", models.DateTimeField(verbose_name="Válido Hasta")),
                (
                    "requester_notes",
                    models.TextField(blank=True, verbose_name="Notas del Solicitante"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notas Internas"),
                ),
                (
                    "approved_level_1_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_approved_l1",
                        to="personnel.personnelprofile",
                        verbose_name="Aprobado L1 por",
                    ),
                ),
                (
                    "approved_level_2_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_approved_l2",
                        to="personnel.personnelprofile",
                        verbose_name="Aprobado L2 por",
                    ),
                ),
                (
                    "approved_level_3_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_approved_l3",
                        to="personnel.personnelprofile",
                        verbose_name="Aprobado L3 por",
                    ),
                ),
                (
                    "distributor_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens",
                        to="maintenance.distributorcenter",
                        verbose_name="Centro de Distribución",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens_received",
                        to="personnel.personnelprofile",
                        verbose_name="Beneficiario",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_rejected",
                        to="personnel.personnelprofile",
                        verbose_name="Rechazado por",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_validated",
                        to="personnel.personnelprofile",
                        verbose_name="Validado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Token",
                "verbose_name_plural": "Solicitudes de Token",
                "db_table": "token_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UniformDeliveryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "is_delivered",
                    models.BooleanField(default=False, verbose_name="Entregado"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Entrega"
                    ),
                ),
                (
                    "delivery_photo_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tokens/uniforms/%Y/%m/",
                        verbose_name="Foto de Entrega 1",
                    ),
                ),
                (
                    "delivery_photo_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tokens/uniforms/%Y/%m/",
                        verbose_name="Foto de Entrega 2",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tokens/signatures/%Y/%m/",
                        verbose_name="Firma Digital",
                    ),
                ),
                (
                    "delivery_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación de Entrega"
                    ),
                ),
                (
                    "delivery_notes",
                    models.TextField(blank=True, verbose_name="Notas de Entrega"),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uniforms_delivered",
                        to="personnel.personnelprofile",
                        verbose_name="Entregado por",
                    ),
                ),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniform_delivery_detail",
                        to="tokens.tokenrequest",
                        verbose_name="Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Entrega de Uniforme",
                "verbose_name_plural": "Detalles de Entrega de Uniforme",
                "db_table": "token_uniform_delivery_detail",
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Abreviatura"
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "token_unit_of_measure",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UniformItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("SHIRT", "Camisa"),
                            ("PANTS", "Pantalón"),
                            ("JACKET", "Chaqueta"),
                            ("SHOES", "Zapatos"),
                            ("BOOTS", "Botas"),
                            ("HAT", "Gorra"),
                            ("HELMET", "Casco"),
                            ("VEST", "Chaleco"),
                            ("GLOVES", "Guantes"),
                            ("BELT", "Cinturón"),
                            ("BADGE", "Credencial"),
                            ("OVERALL", "Overol"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Prenda",
                    ),
                ),
                (
                    "custom_description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Descripción Personalizada",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "Extra Pequeño"),
                            ("S", "Pequeño"),
                            ("M", "Mediano"),
                            ("L", "Grande"),
                            ("XL", "Extra Grande"),
                            ("XXL", "Doble Extra Grande"),
                            ("XXXL", "Triple Extra Grande"),
                            ("35", "Talla 35"),
                            ("36", "Talla 36"),
                            ("37", "Talla 37"),
                            ("38", "Talla 38"),
                            ("39", "Talla 39"),
                            ("40", "Talla 40"),
                            ("41", "Talla 41"),
                            ("42", "Talla 42"),
                            ("43", "Talla 43"),
                            ("44", "Talla 44"),
                            ("45", "Talla 45"),
                            ("NA", "No Aplica"),
                        ],
                        default="NA",
                        max_length=10,
                        verbose_name="Talla",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, verbose_name="Color"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "requires_return",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Devolución"
                    ),
                ),
                (
                    "return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Devolución"
                    ),
                ),
                (
                    "returned",
                    models.BooleanField(default=False, verbose_name="Devuelto"),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Devolución Real"
                    ),
                ),
                (
                    "uniform_delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tokens.uniformdeliverydetail",
                        verbose_name="Entrega de Uniforme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Uniforme",
                "verbose_name_plural": "Items de Uniforme",
                "db_table": "token_uniform_item",
            },
        ),
        migrations.CreateModel(
            name="SubstitutionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ABSENCE", "Ausencia"),
                            ("VACATION", "Vacaciones"),
                            ("MEDICAL_LEAVE", "Licencia Médica"),
                            ("TRAINING", "Capacitación"),
                            ("PROMOTION", "Promoción Temporal"),
                            ("EMERGENCY", "Emergencia"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(blank=True, verbose_name="Detalle del Motivo"),
                ),
                (
                    "assumed_functions",
                    models.TextField(verbose_name="Funciones a Asumir"),
                ),
                ("start_date", models.DateField(verbose_name="Fecha Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha Fin")),
                (
                    "specific_schedule",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Horario Específico"
                    ),
                ),
                (
                    "additional_compensation",
                    models.BooleanField(
                        default=False, verbose_name="Compensación Adicional"
                    ),
                ),
                (
                    "compensation_notes",
                    models.TextField(blank=True, verbose_name="Notas de Compensación"),
                ),
                (
                    "substituted_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substitutions_received",
                        to="personnel.personnelprofile",
                        verbose_name="Personal Sustituido",
                    ),
                ),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_detail",
                        to="tokens.tokenrequest",
                        verbose_name="Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Sustitución",
                "verbose_name_plural": "Detalles de Sustitución",
                "db_table": "token_substitution_detail",
            },
        ),
        migrations.CreateModel(
            name="ShiftChangeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Motivo Personal"),
                            ("MEDICAL", "Cita Médica"),
                            ("EDUCATION", "Estudios"),
                            ("FAMILY", "Asunto Familiar"),
                            ("TRANSPORT", "Transporte"),
                            ("MUTUAL_AGREEMENT", "Acuerdo Mutuo"),
                            ("OPERATIONAL", "Necesidad Operativa"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Motivo del Cambio",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(blank=True, verbose_name="Detalle del Motivo"),
                ),
                (
                    "current_shift_name",
                    models.CharField(max_length=100, verbose_name="Turno Actual"),
                ),
                (
                    "current_shift_start",
                    models.TimeField(verbose_name="Hora Inicio Turno Actual"),
                ),
                (
                    "current_shift_end",
                    models.TimeField(verbose_name="Hora Fin Turno Actual"),
                ),
                (
                    "new_shift_name",
                    models.CharField(max_length=100, verbose_name="Nuevo Turno"),
                ),
                (
                    "new_shift_start",
                    models.TimeField(verbose_name="Hora Inicio Nuevo Turno"),
                ),
                (
                    "new_shift_end",
                    models.TimeField(verbose_name="Hora Fin Nuevo Turno"),
                ),
                ("change_date", models.DateField(verbose_name="Fecha del Cambio")),
                (
                    "is_permanent",
                    models.BooleanField(default=False, verbose_name="Es Permanente"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Fin (si temporal)"
                    ),
                ),
                (
                    "exchange_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="Intercambio Confirmado"
                    ),
                ),
                (
                    "exchange_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_exchanges",
                        to="personnel.personnelprofile",
                        verbose_name="Intercambio con",
                    ),
                ),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_change_detail",
                        to="tokens.tokenrequest",
                        verbose_name="Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Cambio de Turno",
                "verbose_name_plural": "Detalles de Cambio de Turno",
                "db_table": "token_shift_change_detail",
            },
        ),
        migrations.CreateModel(
            name="RateChangeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("TEMPORARY_ASSIGNMENT", "Asignación Temporal"),
                            ("SPECIAL_PROJECT", "Proyecto Especial"),
                            ("ADDITIONAL_RESPONSIBILITY", "Responsabilidad Adicional"),
                            ("COVERAGE", "Cobertura de Puesto"),
                            ("INCENTIVE", "Incentivo"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Motivo del Cambio",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(blank=True, verbose_name="Detalle del Motivo"),
                ),
                (
                    "current_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tasa Actual"
                    ),
                ),
                (
                    "new_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Nueva Tasa"
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        default="Horaria", max_length=50, verbose_name="Tipo de Tasa"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha Fin")),
                (
                    "additional_functions",
                    models.TextField(blank=True, verbose_name="Funciones Adicionales"),
                ),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_change_detail",
                        to="tokens.tokenrequest",
                        verbose_name="Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Cambio de Tasa",
                "verbose_name_plural": "Detalles de Cambio de Tasa",
                "db_table": "token_rate_change_detail",
            },
        ),
        migrations.CreateModel(
            name="PermitHourDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Cita Médica"),
                            ("PERSONAL", "Asunto Personal"),
                            ("BANK", "Trámite Bancario"),
                            ("GOVERNMENT", "Trámite Gubernamental"),
                            ("FAMILY", "Asunto Familiar"),
                            ("EDUCATION", "Asunto Educativo"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Motivo",
                    ),
                ),
                (
                    "reason_description",
                    models.TextField(blank=True, verbose_name="Descripción del Motivo"),
                ),
                (
                    "hours_requested",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Horas Solicitadas"
                    ),
                ),
                ("exit_time", models.TimeField(verbose_name="Hora de Salida")),
                (
                    "expected_return_time",
                    models.TimeField(verbose_name="Hora de Retorno Esperada"),
                ),
                (
                    "actual_exit_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Salida Real"
                    ),
                ),
                (
                    "actual_return_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Retorno Real"
                    ),
                ),
                (
                    "with_pay",
                    models.BooleanField(
                        default=True, verbose_name="Con Goce de Sueldo"
                    ),
                ),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permit_hour_detail",
                        to="tokens.tokenrequest",
                        verbose_name="Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Permiso por Hora",
                "verbose_name_plural": "Detalles Permiso por Hora",
                "db_table": "token_permit_hour_detail",
            },
        ),
        migrations.CreateModel(
            name="PermitDayDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "date_selection_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Día Único"),
                            ("RANGE", "Rango de Días"),
                            ("MULTIPLE", "Días Múltiples"),
                        ],
                        default="SINGLE",
                        max_length=20,
                        verbose_name="Tipo de Selección",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Cita Médica"),
                            ("FAMILY", "Asunto Familiar"),
                            ("PERSONAL", "Asunto Personal"),
                            ("LEGAL", "Asunto Legal/Trámite"),
                            ("EDUCATION", "Educación/Capacitación"),
                            ("BEREAVEMENT", "Duelo"),
                            ("WEDDING", "Matrimonio"),
                            ("PATERNITY", "Paternidad"),
                            ("MATERNITY", "Maternidad"),
                            ("VACATION", "Vacaciones"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(blank=True, verbose_name="Detalle del Motivo"),
                ),
                (
                    "with_pay",
                    models.BooleanField(
                        default=True, verbose_name="Con Goce de Sueldo"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permit_day_detail",
                        to="tokens.tokenrequest",
                        verbose_name="Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Permiso por Día",
                "verbose_name_plural": "Detalles de Permiso por Día",
                "db_table": "token_permit_day_detail",
            },
        ),
        migrations.CreateModel(
            name="PermitDayDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="Notas"),
                ),
                (
                    "permit_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_dates",
                        to="tokens.permitdaydetail",
                        verbose_name="Permiso por Día",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fecha de Permiso",
                "verbose_name_plural": "Fechas de Permiso",
                "db_table": "token_permit_day_date",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="OvertimeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "overtime_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Horas Extra Regulares"),
                            ("HOLIDAY", "Horas en Feriado"),
                            ("WEEKEND", "Horas en Fin de Semana"),
                            ("NIGHT", "Horas Nocturnas"),
                            ("DOUBLE", "Doble Turno"),
                        ],
                        default="REGULAR",
                        max_length=20,
                        verbose_name="Tipo de Hora Extra",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Demanda de Producción"),
                            ("DEADLINE", "Cumplimiento de Plazo"),
                            ("COVERAGE", "Cobertura de Personal"),
                            ("EMERGENCY", "Emergencia"),
                            ("SPECIAL_PROJECT", "Proyecto Especial"),
                            ("INVENTORY", "Inventario"),
                            ("MAINTENANCE", "Mantenimiento"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(blank=True, verbose_name="Detalle del Motivo"),
                ),
                (
                    "overtime_date",
                    models.DateField(verbose_name="Fecha de Horas Extra"),
                ),
                ("start_time", models.TimeField(verbose_name="Hora de Inicio")),
                ("end_time", models.TimeField(verbose_name="Hora de Fin")),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total de Horas",
                    ),
                ),
                (
                    "pay_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=3,
                        verbose_name="Multiplicador de Pago",
                    ),
                ),
                (
                    "assigned_task",
                    models.TextField(blank=True, verbose_name="Tarea Asignada"),
                ),
                (
                    "was_completed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Completado"
                    ),
                ),
                (
                    "actual_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora Real de Inicio"
                    ),
                ),
                (
                    "actual_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora Real de Fin"
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Horas Reales",
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(blank=True, verbose_name="Notas de Cumplimiento"),
                ),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_detail",
                        to="tokens.tokenrequest",
                        verbose_name="Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Horas Extra",
                "verbose_name_plural": "Detalles de Horas Extra",
                "db_table": "token_overtime_detail",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor Unitario",
                    ),
                ),
                (
                    "requires_return",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Devolución"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Categoría"
                    ),
                ),
                (
                    "unit_of_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="tokens.unitofmeasure",
                        verbose_name="Unidad de Medida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiales",
                "db_table": "token_material",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExitPassItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "custom_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Descripción Personalizada",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cantidad"
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor Unitario",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "requires_return",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Devolución"
                    ),
                ),
                (
                    "return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Devolución"
                    ),
                ),
                (
                    "returned",
                    models.BooleanField(default=False, verbose_name="Devuelto"),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Devolución Real"
                    ),
                ),
                (
                    "returned_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cantidad Devuelta",
                    ),
                ),
                (
                    "return_notes",
                    models.TextField(blank=True, verbose_name="Notas de Devolución"),
                ),
                (
                    "exit_pass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tokens.exitpassdetail",
                        verbose_name="Pase de Salida",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exit_pass_items",
                        to="tokens.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exit_pass_items",
                        to="maintenance.productmodel",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pase de Salida",
                "verbose_name_plural": "Items de Pase de Salida",
                "db_table": "token_exit_pass_item",
            },
        ),
        migrations.AddField(
            model_name="exitpassdetail",
            name="token",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exit_pass_detail",
                to="tokens.tokenrequest",
                verbose_name="Token",
            ),
        ),
        migrations.AddIndex(
            model_name="tokenrequest",
            index=models.Index(
                fields=["token_code"], name="token_reque_token_c_1e86b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenrequest",
            index=models.Index(
                fields=["display_number"], name="token_reque_display_8c2ee5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenrequest",
            index=models.Index(
                fields=["status", "created_at"], name="token_reque_status_d80d54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tokenrequest",
            index=models.Index(
                fields=["personnel", "created_at"],
                name="token_reque_personn_763886_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tokenrequest",
            index=models.Index(
                fields=["distributor_center", "status"],
                name="token_reque_distrib_70246b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tokenrequest",
            index=models.Index(
                fields=["token_type", "status"], name="token_reque_token_t_1437dc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permitdaydate",
            unique_together={("permit_day", "date")},
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["code"], name="token_mater_code_b04ce9_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["category"], name="token_mater_categor_11d4ca_idx"
            ),
        ),
    ]
