# Generated by Django 5.0.6 on 2026-01-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="material",
            new_name="app_token_m_code_64ee54_idx",
            old_name="token_mater_code_b04ce9_idx",
        ),
        migrations.RenameIndex(
            model_name="material",
            new_name="app_token_m_categor_6aea8c_idx",
            old_name="token_mater_categor_11d4ca_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenrequest",
            new_name="app_token_r_token_c_e0cfc0_idx",
            old_name="token_reque_token_c_1e86b5_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenrequest",
            new_name="app_token_r_display_8c1d85_idx",
            old_name="token_reque_display_8c2ee5_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenrequest",
            new_name="app_token_r_status_b1e354_idx",
            old_name="token_reque_status_d80d54_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenrequest",
            new_name="app_token_r_personn_a5beb4_idx",
            old_name="token_reque_personn_763886_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenrequest",
            new_name="app_token_r_distrib_ebd673_idx",
            old_name="token_reque_distrib_70246b_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenrequest",
            new_name="app_token_r_token_t_6b5cc7_idx",
            old_name="token_reque_token_t_1437dc_idx",
        ),
        migrations.AlterModelTable(
            name="exitpassdetail",
            table="app_token_exit_pass_detail",
        ),
        migrations.AlterModelTable(
            name="exitpassitem",
            table="app_token_exit_pass_item",
        ),
        migrations.AlterModelTable(
            name="material",
            table="app_token_material",
        ),
        migrations.AlterModelTable(
            name="overtimedetail",
            table="app_token_overtime_detail",
        ),
        migrations.AlterModelTable(
            name="permitdaydate",
            table="app_token_permit_day_date",
        ),
        migrations.AlterModelTable(
            name="permitdaydetail",
            table="app_token_permit_day_detail",
        ),
        migrations.AlterModelTable(
            name="permithourdetail",
            table="app_token_permit_hour_detail",
        ),
        migrations.AlterModelTable(
            name="ratechangedetail",
            table="app_token_rate_change_detail",
        ),
        migrations.AlterModelTable(
            name="shiftchangedetail",
            table="app_token_shift_change_detail",
        ),
        migrations.AlterModelTable(
            name="substitutiondetail",
            table="app_token_substitution_detail",
        ),
        migrations.AlterModelTable(
            name="tokenrequest",
            table="app_token_request",
        ),
        migrations.AlterModelTable(
            name="uniformdeliverydetail",
            table="app_token_uniform_delivery_detail",
        ),
        migrations.AlterModelTable(
            name="uniformitem",
            table="app_token_uniform_item",
        ),
        migrations.AlterModelTable(
            name="unitofmeasure",
            table="app_token_unit_of_measure",
        ),
    ]
