# Generated by Django 5.0.6 on 2026-01-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_rename_token_mater_code_b04ce9_idx_app_token_m_code_64ee54_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenrequest",
            name="approved_level_1_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tokens/approvals/photos/%Y/%m/",
                verbose_name="Foto Aprobación L1",
            ),
        ),
        migrations.AddField(
            model_name="tokenrequest",
            name="approved_level_1_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tokens/approvals/signatures/%Y/%m/",
                verbose_name="Firma Aprobación L1",
            ),
        ),
        migrations.AddField(
            model_name="tokenrequest",
            name="approved_level_2_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tokens/approvals/photos/%Y/%m/",
                verbose_name="Foto Aprobación L2",
            ),
        ),
        migrations.AddField(
            model_name="tokenrequest",
            name="approved_level_2_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tokens/approvals/signatures/%Y/%m/",
                verbose_name="Firma Aprobación L2",
            ),
        ),
        migrations.AddField(
            model_name="tokenrequest",
            name="approved_level_3_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tokens/approvals/photos/%Y/%m/",
                verbose_name="Foto Aprobación L3",
            ),
        ),
        migrations.AddField(
            model_name="tokenrequest",
            name="approved_level_3_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tokens/approvals/signatures/%Y/%m/",
                verbose_name="Firma Aprobación L3",
            ),
        ),
    ]
