# Generated by Django 5.0.6 on 2026-01-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0003_add_approval_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenrequest",
            name="validation_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tokens/validations/signatures/%Y/%m/",
                verbose_name="Firma de Validación",
            ),
        ),
        migrations.AddField(
            model_name="tokenrequest",
            name="validation_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tokens/validations/photos/%Y/%m/",
                verbose_name="Foto de Validación",
            ),
        ),
        migrations.AddField(
            model_name="tokenrequest",
            name="validation_notes",
            field=models.TextField(
                blank=True,
                verbose_name="Notas de Validación",
            ),
        ),
    ]
