# Generated by Django 5.0.6 on 2026-01-10 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0009_make_personal_fields_optional"),
        ("tokens", "0004_add_validation_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenrequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_level_1", "Puede aprobar tokens nivel 1"),
                    ("can_approve_level_2", "Puede aprobar tokens nivel 2"),
                    ("can_approve_level_3", "Puede aprobar tokens nivel 3"),
                    ("can_approve_token", "Puede aprobar tokens (cualquier nivel)"),
                    ("can_reject_token", "Puede rechazar tokens"),
                    ("can_cancel_token", "Puede cancelar tokens"),
                    ("can_validate_token", "Puede validar tokens en porteria"),
                    ("can_download_pdf", "Puede descargar PDF de tokens"),
                    ("can_download_receipt", "Puede descargar recibos de tokens"),
                    ("can_print_token", "Puede imprimir tokens"),
                    ("can_complete_delivery", "Puede completar entrega de uniformes"),
                    ("can_view_reports", "Puede ver reportes de tokens"),
                    ("can_export_data", "Puede exportar datos de tokens"),
                ],
                "verbose_name": "Solicitud de Token",
                "verbose_name_plural": "Solicitudes de Token",
            },
        ),
        migrations.AddField(
            model_name="exitpassdetail",
            name="is_external",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el pase es para un proveedor/persona externa",
                verbose_name="Es persona externa",
            ),
        ),
        migrations.AddField(
            model_name="exitpassitem",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso en kilogramos del material",
                max_digits=10,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="tokenrequest",
            name="personnel",
            field=models.ForeignKey(
                blank=True,
                help_text="Puede ser nulo para pases de salida de personas externas",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tokens_received",
                to="personnel.personnelprofile",
                verbose_name="Beneficiario",
            ),
        ),
        migrations.CreateModel(
            name="ExternalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre completo"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Empresa"
                    ),
                ),
                (
                    "identification",
                    models.CharField(
                        blank=True,
                        help_text="Número de identidad o RTN",
                        max_length=50,
                        verbose_name="Identificación",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Externa",
                "verbose_name_plural": "Personas Externas",
                "db_table": "app_token_external_person",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="app_token_e_name_2b2374_idx"),
                    models.Index(
                        fields=["company"], name="app_token_e_company_27adbb_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="app_token_e_is_acti_44f522_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="exitpassdetail",
            name="external_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exit_passes",
                to="tokens.externalperson",
                verbose_name="Persona externa",
            ),
        ),
    ]
