# Generated by Django 4.2.19 on 2026-01-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0005_add_external_person_and_exit_pass_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenrequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_level_1", "Puede aprobar tokens nivel 1"),
                    ("can_approve_level_2", "Puede aprobar tokens nivel 2"),
                    ("can_approve_level_3", "Puede aprobar tokens nivel 3"),
                    ("can_approve_token", "Puede aprobar tokens (cualquier nivel)"),
                    ("can_reject_token", "Puede rechazar tokens"),
                    ("can_cancel_token", "Puede cancelar tokens"),
                    ("can_validate_token", "Puede validar tokens en porteria"),
                    (
                        "can_validate_payroll",
                        "Puede marcar tokens como utilizados (Planilla)",
                    ),
                    ("can_download_pdf", "Puede descargar PDF de tokens"),
                    ("can_download_receipt", "Puede descargar recibos de tokens"),
                    ("can_print_token", "Puede imprimir tokens"),
                    ("can_complete_delivery", "Puede completar entrega de uniformes"),
                    ("can_view_reports", "Puede ver reportes de tokens"),
                    ("can_export_data", "Puede exportar datos de tokens"),
                ],
                "verbose_name": "Solicitud de Token",
                "verbose_name_plural": "Solicitudes de Token",
            },
        ),
    ]
