# Generated by Django 4.2.19 on 2026-03-11 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0006_alter_tokenrequest_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeReasonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Motivo de Hora Extra",
                "verbose_name_plural": "Motivos de Horas Extra",
                "db_table": "app_token_overtime_reason",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OvertimeTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "default_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=3,
                        verbose_name="Multiplicador por Defecto",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de Hora Extra",
                "verbose_name_plural": "Tipos de Horas Extra",
                "db_table": "app_token_overtime_type",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="uniformitem",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uniform_items",
                to="tokens.material",
                verbose_name="Material",
            ),
        ),
        migrations.AlterField(
            model_name="overtimedetail",
            name="overtime_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Horas Extra Regulares"),
                    ("HOLIDAY", "Horas en Feriado"),
                    ("WEEKEND", "Horas en Fin de Semana"),
                    ("NIGHT", "Horas Nocturnas"),
                    ("DOUBLE", "Doble Turno"),
                ],
                default="REGULAR",
                max_length=20,
                verbose_name="Tipo de Hora Extra (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="overtimedetail",
            name="reason",
            field=models.CharField(
                choices=[
                    ("PRODUCTION", "Demanda de Producción"),
                    ("DEADLINE", "Cumplimiento de Plazo"),
                    ("COVERAGE", "Cobertura de Personal"),
                    ("EMERGENCY", "Emergencia"),
                    ("SPECIAL_PROJECT", "Proyecto Especial"),
                    ("INVENTORY", "Inventario"),
                    ("MAINTENANCE", "Mantenimiento"),
                    ("OTHER", "Otro"),
                ],
                max_length=20,
                verbose_name="Motivo (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="tokenrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("PENDING_L1", "Pendiente de aprobación"),
                    ("PENDING_L2", "Pendiente de aprobación"),
                    ("PENDING_L3", "Pendiente de aprobación"),
                    ("APPROVED", "Abierto"),
                    ("USED", "Finalizado"),
                    ("EXPIRED", "Vencido"),
                    ("CANCELLED", "Cerrado"),
                    ("REJECTED", "Cerrado"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SHIRT", "Camisa"),
                    ("PANTS", "Pantalón"),
                    ("JACKET", "Chaqueta"),
                    ("SHOES", "Zapatos"),
                    ("BOOTS", "Botas"),
                    ("HAT", "Gorra"),
                    ("HELMET", "Casco"),
                    ("VEST", "Chaleco"),
                    ("GLOVES", "Guantes"),
                    ("BELT", "Cinturón"),
                    ("BADGE", "Credencial"),
                    ("OVERALL", "Overol"),
                    ("OTHER", "Otro"),
                ],
                max_length=20,
                verbose_name="Tipo de Prenda (legacy)",
            ),
        ),
        migrations.AddField(
            model_name="overtimedetail",
            name="overtime_type_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overtime_details",
                to="tokens.overtimetypemodel",
                verbose_name="Tipo de Hora Extra",
            ),
        ),
        migrations.AddField(
            model_name="overtimedetail",
            name="reason_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overtime_details",
                to="tokens.overtimereasonmodel",
                verbose_name="Motivo",
            ),
        ),
    ]
