# Generated by Django 4.2.19 on 2026-03-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0007_overtimereasonmodel_overtimetypemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimedetail',
            name='overtime_type_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_details', to='tokens.overtimetypemodel', verbose_name='Tipo de Hora Extra'),
        ),
        migrations.AlterField(
            model_name='overtimedetail',
            name='reason_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_details', to='tokens.overtimereasonmodel', verbose_name='Motivo'),
        ),
    ]
