# Generated by Django 4.2.19 on 2026-03-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0008_alter_overtimedetail_overtime_type_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimereasonmodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='overtimetypemodel',
            name='code',
        ),
        migrations.AddField(
            model_name='overtimereasonmodel',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='overtimetypemodel',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='overtimedetail',
            name='overtime_type_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_details', to='tokens.overtimetypemodel', verbose_name='Tipo de Hora Extra'),
        ),
        migrations.AlterField(
            model_name='overtimedetail',
            name='reason_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_details', to='tokens.overtimereasonmodel', verbose_name='Motivo'),
        ),
    ]
