# Generated by Django 4.2.19 on 2026-03-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_countrymodel_distributorcenter_country_and_more'),
        ('tokens', '0009_remove_overtimereasonmodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitpassitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_pass_items', to='tokens.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='exitpassitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_pass_items', to='maintenance.productmodel', verbose_name='Producto'),
        ),
    ]
