# Generated by Django 4.2.19 on 2026-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0010_alter_exitpassitem_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitpassitem',
            name='unit_label',
            field=models.CharField(blank=True, default='', help_text='Ej: Par, Cajas, Unidades, Litros', max_length=50, verbose_name='Etiqueta de Unidad'),
        ),
    ]
