# Generated by Django 4.2.19 on 2026-04-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0011_exitpassitem_unit_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas del Segmento')),
                ('pay_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Ej: 2.40 para 240%, 3.00 para 300%', max_digits=5, verbose_name='Multiplicador de Pago (%)')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('overtime_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='tokens.overtimedetail', verbose_name='Detalle de Hora Extra')),
                ('overtime_type_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overtime_segments', to='tokens.overtimetypemodel', verbose_name='Tipo de Hora Extra')),
            ],
            options={
                'verbose_name': 'Segmento de Hora Extra',
                'verbose_name_plural': 'Segmentos de Hora Extra',
                'db_table': 'app_token_overtime_segment',
                'ordering': ['sequence', 'start_time'],
            },
        ),
    ]
