# Generated by Django 4.2.16 on 2026-05-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repack', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='repackentry',
            new_name='repack_entr_session_4dc58f_idx',
            old_name='repack_entry_sess_idx',
        ),
        migrations.RenameIndex(
            model_name='repackentry',
            new_name='repack_entr_materia_d1f035_idx',
            old_name='repack_entry_mat_idx',
        ),
        migrations.RenameIndex(
            model_name='repackentry',
            new_name='repack_entr_expirat_04584a_idx',
            old_name='repack_entry_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='repacksession',
            new_name='repack_sess_personn_33014b_idx',
            old_name='repack_sess_personn_idx',
        ),
        migrations.RenameIndex(
            model_name='repacksession',
            new_name='repack_sess_distrib_1ea0a7_idx',
            old_name='repack_sess_dc_idx',
        ),
    ]
