# Generated by Django 4.2.16 on 2026-04-28 07:46

import apps.workstation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkstationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('type', models.CharField(choices=[('RISKS', 'Riesgos del área'), ('PROHIBITIONS', 'Prohibiciones del área'), ('TRIGGERS', 'Disparador resolución de problemas'), ('SIC_CHART', 'SIC / Pi Crítico'), ('REACTION_PLANS', 'Planes de Reacción'), ('QR_DOCUMENT', 'QR · Documento PDF'), ('QR_EXTERNAL', 'QR · Link externo'), ('IMAGE', 'Imagen'), ('TEXT', 'Texto / Nota'), ('TITLE', 'Título'), ('CLOCK', 'Reloj'), ('DPO', 'Sello DPO')], max_length=20, verbose_name='Tipo')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración')),
                ('grid_x', models.PositiveIntegerField(default=0, verbose_name='X')),
                ('grid_y', models.PositiveIntegerField(default=0, verbose_name='Y')),
                ('grid_w', models.PositiveIntegerField(default=4, verbose_name='Ancho')),
                ('grid_h', models.PositiveIntegerField(default=3, verbose_name='Alto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workstation.workstation')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'db_table': 'workstation_block',
                'ordering': ['workstation', 'grid_y', 'grid_x'],
            },
        ),
        migrations.CreateModel(
            name='WorkstationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(blank=True, default='', max_length=160, verbose_name='Nombre')),
                ('file', models.ImageField(upload_to=apps.workstation.models.workstation_image_upload_path, verbose_name='Archivo')),
                ('alt', models.CharField(blank=True, default='', max_length=160, verbose_name='Texto alternativo')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workstation.workstation')),
            ],
            options={
                'verbose_name': 'Imagen de Estación',
                'verbose_name_plural': 'Imágenes de Estación',
                'db_table': 'workstation_image',
                'ordering': ['workstation', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='workstation',
        ),
        migrations.AlterUniqueTogether(
            name='workstationprohibition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workstationprohibition',
            name='prohibition',
        ),
        migrations.RemoveField(
            model_name='workstationprohibition',
            name='workstation',
        ),
        migrations.AlterUniqueTogether(
            name='workstationrisk',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workstationrisk',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='workstationrisk',
            name='workstation',
        ),
        migrations.AlterModelOptions(
            name='workstationdocument',
            options={'ordering': ['workstation', 'doc_type', '-created_at'], 'verbose_name': 'Documento de Estación', 'verbose_name_plural': 'Documentos de Estación'},
        ),
        migrations.RemoveField(
            model_name='workstationdocument',
            name='display_order',
        ),
        migrations.AlterField(
            model_name='workstationdocument',
            name='doc_type',
            field=models.CharField(choices=[('SOP', 'SOP — Standard Operating Procedure'), ('OPL', 'OPL — One Point Lesson'), ('OTHER', 'Otro')], default='SOP', max_length=10, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='ReactionPlan',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
        migrations.DeleteModel(
            name='WorkstationProhibition',
        ),
        migrations.DeleteModel(
            name='WorkstationRisk',
        ),
    ]
