# Generated by Django 4.2.19 on 2026-04-20 06:29

import apps.tv.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0006_distributorcenter_location_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TvSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=apps.tv.models._gen_code, max_length=9, unique=True, verbose_name='Código')),
                ('access_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAIRED', 'Pareada'), ('EXPIRED', 'Expirada'), ('REVOKED', 'Revocada')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Último heartbeat')),
                ('paired_at', models.DateTimeField(blank=True, null=True, verbose_name='Pareada en')),
                ('dashboard', models.CharField(choices=[('WORKSTATION', 'Workstation')], default='WORKSTATION', max_length=20, verbose_name='Dashboard')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración')),
                ('label', models.CharField(blank=True, default='', max_length=80, verbose_name='Etiqueta')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('distributor_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv_sessions', to='maintenance.distributorcenter', verbose_name='Centro de distribución')),
                ('paired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tv_sessions_paired', to=settings.AUTH_USER_MODEL, verbose_name='Pareada por')),
            ],
            options={
                'verbose_name': 'Sesión de TV',
                'verbose_name_plural': 'Sesiones de TV',
                'db_table': 'tv_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='tv_session_status_e310ac_idx')],
            },
        ),
    ]
