from .centro_distribucion import DistributorCenterSerializer,RouteModelSerializer, LocationModelSerializer
from .operator import OperatorModelSerializer
from .trailer import TrailerModelSerializer, TransporterModelSerializer