from .centro_distribucion import DistributorCenterSerializer, RouteModelSerializer, LocationModelSerializer
from .operator import OperatorModelSerializer
from .trailer import TrailerModelSerializer, TransporterModelSerializer
from .product import ProductModelSerializer, OutputTypeModelSerializer
from .driver import DriverModelSerializer
from .period import PeriodModelSerializer