# Generated by Django 3.2.20 on 2025-03-03 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0014_alter_outputt2model_pre_sale_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('tipo', models.CharField(choices=[('DAÑOS', 'Daños en la Mercancía'), ('FALTANTES', 'Faltantes'), ('TIEMPOS', 'Tiempos de Entrega'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('descripcion', models.TextField(verbose_name='Descripción del reclamo')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('doc_contenido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_contenido', to='document.documentmodel', verbose_name='Documento del Contenido')),
                ('doc_descarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_descarga', to='document.documentmodel', verbose_name='Documento de Descarga')),
                ('doc_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_producto', to='document.documentmodel', verbose_name='Documento del Producto')),
                ('doc_trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_trailer', to='document.documentmodel', verbose_name='Documento del Tráiler')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='tracker.trackermodel', verbose_name='Tracker asociado')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'app_claim',
            },
        ),
    ]
