# Generated by Django 5.2 on 2025-04-16 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('maintenance', '0005_countrymodel_distributorcenter_country_and_more'),
        ('tracker', '0014_remove_trackermodel_archivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Reclamo',
                'verbose_name_plural': 'Tipos de Reclamos',
                'db_table': 'app_claim_type',
            },
        ),
        migrations.CreateModel(
            name='ClaimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('type', models.CharField(choices=[('CLAIM', 'Claim'), ('ALERT_QUALITY', 'ALERT_QUALITY')], default='CLAIM', max_length=50, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del Reclamo')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('claim_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Claim')),
                ('claim_file', models.FileField(blank=True, null=True, upload_to='claim_files/', verbose_name='Archivo Claim (PDF o Excel)')),
                ('credit_memo_file', models.FileField(blank=True, null=True, upload_to='claim_credit_memos/', verbose_name='Nota de Crédito')),
                ('discard_doc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de Descarte')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('observations_file', models.FileField(blank=True, null=True, upload_to='claim_observations/', verbose_name='Archivo de Observaciones (PDF)')),
                ('claim_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Claim')),
                ('reject_reason', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón de Rechazo')),
                ('approve_observations', models.TextField(blank=True, null=True, verbose_name='Observaciones de Aprobación')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('photos_container_closed', models.ManyToManyField(blank=True, related_name='claims_container_closed', to='document.documentmodel', verbose_name='Fotografías: Contenedor cerrado')),
                ('photos_container_one_open', models.ManyToManyField(blank=True, related_name='claims_container_one_open', to='document.documentmodel', verbose_name='Fotografías: Contenedor con 1 puerta abierta')),
                ('photos_container_top', models.ManyToManyField(blank=True, related_name='claims_container_top', to='document.documentmodel', verbose_name='Fotografías: Vista superior del contenido')),
                ('photos_container_two_open', models.ManyToManyField(blank=True, related_name='claims_container_two_open', to='document.documentmodel', verbose_name='Fotografías: Contenedor con 2 puertas abiertas')),
                ('photos_damaged_boxes', models.ManyToManyField(blank=True, related_name='claims_damaged_boxes', to='document.documentmodel', verbose_name='Fotografías: Cajas dañadas')),
                ('photos_damaged_product_base', models.ManyToManyField(blank=True, related_name='claims_damaged_product_base', to='document.documentmodel', verbose_name='Fotografías: Base de lata/botella dañada')),
                ('photos_damaged_product_dents', models.ManyToManyField(blank=True, related_name='claims_damaged_product_dents', to='document.documentmodel', verbose_name='Fotografías: Abolladuras del producto')),
                ('photos_during_unload', models.ManyToManyField(blank=True, related_name='claims_during_unload', to='document.documentmodel', verbose_name='Fotografías: Durante la descarga')),
                ('photos_grouped_bad_product', models.ManyToManyField(blank=True, related_name='claims_grouped_bad_product', to='document.documentmodel', verbose_name='Fotografías: Producto en mal estado agrupado')),
                ('photos_pallet_damage', models.ManyToManyField(blank=True, related_name='claims_pallet_damage', to='document.documentmodel', verbose_name='Fotografías: Fisuras/abolladuras de pallets')),
                ('photos_production_batch', models.ManyToManyField(blank=True, related_name='claims_production_batch', to='document.documentmodel', verbose_name='Fotografías: Lote de producción')),
                ('photos_repalletized', models.ManyToManyField(blank=True, related_name='claims_repalletized', to='document.documentmodel', verbose_name='Fotografías: Repaletizado de producto dañado')),
                ('tracker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='tracker.trackermodel', verbose_name='Tracker asociado')),
                ('claim_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='imported.claimtypemodel', verbose_name='Tipo de Reclamo')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'app_claim',
            },
        ),
        migrations.CreateModel(
            name='ClaimProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('batch', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_products', to='imported.claimmodel', verbose_name='Reclamo asociado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_products', to='maintenance.productmodel', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Producto del Claim',
                'verbose_name_plural': 'Productos del Claim',
                'db_table': 'app_claim_product',
            },
        ),
    ]
