# Generated by Django 4.2.19 on 2025-03-18 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0019_alter_outputt2model_pre_sale_date"),
        ("document", "0002_auto_20250303_2300"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imported", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimmodel",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="claimmodel",
            name="doc_contenido",
        ),
        migrations.RemoveField(
            model_name="claimmodel",
            name="doc_descarga",
        ),
        migrations.RemoveField(
            model_name="claimmodel",
            name="doc_producto",
        ),
        migrations.RemoveField(
            model_name="claimmodel",
            name="doc_trailer",
        ),
        migrations.RemoveField(
            model_name="claimmodel",
            name="tipo",
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="claim_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="claim_files/",
                verbose_name="Archivo Claim (PDF o Excel)",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="claim_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Claim"
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="claim_type",
            field=models.CharField(
                choices=[
                    ("FALTANTE", "Faltante"),
                    ("SOBRANTE", "Sobrante"),
                    ("DAÑOS_CALIDAD_TRANSPORTE", "Daños por Calidad y Transporte"),
                ],
                default="FALTANTE",
                max_length=50,
                verbose_name="Tipo de Reclamo",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="credit_memo_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="claim_credit_memos/",
                verbose_name="Nota de Crédito",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción del Reclamo"
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="discard_doc",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Documento de Descarte",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="observations",
            field=models.TextField(blank=True, null=True, verbose_name="Observaciones"),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="observations_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="claim_observations/",
                verbose_name="Archivo de Observaciones (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_container_closed",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_container_closed",
                to="document.documentmodel",
                verbose_name="Fotografías: Contenedor cerrado",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_container_one_open",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_container_one_open",
                to="document.documentmodel",
                verbose_name="Fotografías: Contenedor con 1 puerta abierta",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_container_top",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_container_top",
                to="document.documentmodel",
                verbose_name="Fotografías: Vista superior del contenido",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_container_two_open",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_container_two_open",
                to="document.documentmodel",
                verbose_name="Fotografías: Contenedor con 2 puertas abiertas",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_damaged_boxes",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_damaged_boxes",
                to="document.documentmodel",
                verbose_name="Fotografías: Cajas dañadas",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_damaged_product_base",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_damaged_product_base",
                to="document.documentmodel",
                verbose_name="Fotografías: Base de lata/botella dañada",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_damaged_product_dents",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_damaged_product_dents",
                to="document.documentmodel",
                verbose_name="Fotografías: Abolladuras del producto",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_during_unload",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_during_unload",
                to="document.documentmodel",
                verbose_name="Fotografías: Durante la descarga",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_grouped_bad_product",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_grouped_bad_product",
                to="document.documentmodel",
                verbose_name="Fotografías: Producto en mal estado agrupado",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_pallet_damage",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_pallet_damage",
                to="document.documentmodel",
                verbose_name="Fotografías: Fisuras/abolladuras de pallets",
            ),
        ),
        migrations.AddField(
            model_name="claimmodel",
            name="photos_repalletized",
            field=models.ManyToManyField(
                blank=True,
                related_name="claims_repalletized",
                to="document.documentmodel",
                verbose_name="Fotografías: Repaletizado de producto dañado",
            ),
        ),
        migrations.AlterField(
            model_name="claimmodel",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims_assigned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado a",
            ),
        ),
        migrations.AlterField(
            model_name="claimmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_REVISION", "En Revisión"),
                    ("RECHAZADO", "Rechazado"),
                    ("APROBADO", "Aprobado"),
                ],
                default="PENDIENTE",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="claimmodel",
            name="tracker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="tracker.trackermodel",
                verbose_name="Tracker asociado",
            ),
        ),
    ]
