# Generated by Django 4.2.19 on 2025-03-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imported", "0002_remove_claimmodel_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimmodel",
            name="claim_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Código de Claim"
            ),
        ),
    ]
