# Generated by Django 4.2.19 on 2025-03-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0005_countrymodel_distributorcenter_country_and_more"),
        ("imported", "0003_claimmodel_claim_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimmodel",
            name="type",
            field=models.CharField(
                choices=[("CLAIM", "Claim"), ("ALERT_QUALITY", "ALERT_QUALITY")],
                default="CLAIM",
                max_length=50,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="ClaimProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_products",
                        to="imported.claimmodel",
                        verbose_name="Reclamo asociado",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_products",
                        to="maintenance.productmodel",
                        verbose_name="Producto asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo Base",
                "verbose_name_plural": "Modelos Base",
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
