# Generated by Django 4.2.19 on 2025-03-31 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0023_alter_outputt2model_pre_sale_date"),
        ("imported", "0004_claimmodel_type_claimproductmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimmodel",
            name="tracker",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim",
                to="tracker.trackermodel",
                verbose_name="Tracker asociado",
            ),
        ),
    ]
