# Generated by Django 4.2.19 on 2025-04-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imported", "0005_alter_claimmodel_tracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimproductmodel",
            name="batch",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Lote"
            ),
        ),
    ]
