# Generated by Django 4.2.20 on 2025-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imported', '0006_claimproductmodel_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimmodel',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón de Rechazo'),
        ),
    ]
