# Generated by Django 4.2.19 on 2025-04-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("imported", "0006_claimproductmodel_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Reclamo",
                "verbose_name_plural": "Tipos de Reclamos",
                "db_table": "app_claim_type",
            },
        ),
        migrations.AlterField(
            model_name="claimmodel",
            name="claim_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="imported.claimtypemodel",
                verbose_name="Tipo de Reclamo",
            ),
        ),
    ]
