# Generated by Django 4.2.19 on 2025-04-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imported", "0007_claimtypemodel_alter_claimmodel_claim_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="claimproductmodel",
            options={
                "verbose_name": "Producto del Claim",
                "verbose_name_plural": "Productos del Claim",
            },
        ),
        migrations.AlterModelTable(
            name="claimproductmodel",
            table="app_claim_product",
        ),
    ]
