# Generated by Django 4.2.20 on 2025-04-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imported', '0007_claimmodel_reject_reason'),
        ('imported', '0008_alter_claimproductmodel_options_and_more'),
    ]

    operations = [
    ]
