# Generated by Django 4.2.20 on 2025-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imported', '0009_merge_20250406_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimmodel',
            name='approve_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de Aprobación'),
        ),
    ]
