# Generated by Django 4.2.19 on 2025-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imported", "0010_claimmodel_approve_observations"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimmodel",
            name="production_batch_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="claim_production_batches/",
                verbose_name="Archivo de Lotes de Producción (PDF)",
            ),
        ),
    ]
