# Generated by Django 4.2.20 on 2025-04-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_documentmodel_folder_documentmodel_subfolder_and_more'),
        ('imported', '0011_claimmodel_production_batch_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimmodel',
            name='production_batch_file',
        ),
        migrations.AddField(
            model_name='claimmodel',
            name='photos_production_batch',
            field=models.ManyToManyField(blank=True, related_name='claims_production_batch', to='document.documentmodel', verbose_name='Fotografías: Lote de producción'),
        ),
    ]
