# Generated by Django 3.2.20 on 2023-11-05 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_alter_productmodel_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_distributor_center', to='maintenance.distributorcenter', verbose_name='Centro de distribución')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='maintenance.productmodel', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('module', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('ADMIN', 'ADMIN')], max_length=50, verbose_name='Modulo')),
                ('origin_id', models.IntegerField(blank=True, null=True, verbose_name='Id de origen')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Aplicado')),
                ('applied_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aplicación')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('BALANCE', 'Balance')], default='IN', max_length=50, verbose_name='Tipo de movimiento')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('initial_quantity', models.IntegerField(default=0, verbose_name='Cantidad inicial')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movement_distributor_center', to='maintenance.distributorcenter', verbose_name='Centro de distribución')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movement_product', to='inventory.inventorymodel', verbose_name='Inventario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movement_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'db_table': 'inventory_movement',
            },
        ),
    ]
