# Generated by Django 3.2.20 on 2024-02-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_trackermodel_transfer_number'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovementmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inventorymovementmodel',
            name='distributor_center',
        ),
        migrations.RemoveField(
            model_name='inventorymovementmodel',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='inventorymovementmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='inventorymovementmodel',
            name='tracker_detail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movement_tracking', to='tracker.trackerdetailproductmodel', verbose_name='Tracking'),
        ),
        migrations.AlterField(
            model_name='inventorymovementmodel',
            name='module',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('ADMIN', 'ADMIN'), ('ORDER', 'ORDER')], max_length=50, verbose_name='Modulo'),
        ),
        migrations.DeleteModel(
            name='InventoryModel',
        ),
    ]
