# Generated by Django 3.2.20 on 2023-12-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20231117_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovementmodel',
            name='module',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('ADMIN', 'ADMIN'), ('ORDER', 'ORDER')], max_length=50, verbose_name='Modulo'),
        ),
    ]
