# Generated by Django 3.2.20 on 2023-08-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Centro de Distribución',
                'verbose_name_plural': 'Centros de Distribución',
                'db_table': 'centro_distribucion',
            },
        ),
    ]
