# Generated by Django 3.2.20 on 2023-09-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direction', models.CharField(max_length=50, null=True, verbose_name='Dirección')),
                ('country_code', models.CharField(max_length=5, null=True, verbose_name='Código de País')),
            ],
            options={
                'verbose_name': 'Centro de Distribución',
                'verbose_name_plural': 'Centros de Distribución',
                'db_table': 'distributor_center',
            },
        ),
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('sap_code', models.CharField(max_length=10, unique=True, verbose_name='Código SAP')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, error_messages={'unique': 'Ya existe una localización con este código'}, max_length=50, null=True, unique=True, verbose_name='Código')),
                ('distributor_center', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_distributor_center', to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
            ],
            options={
                'verbose_name': 'Localización',
                'verbose_name_plural': 'Localizaciones',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='OutputTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('required_details', models.BooleanField(default=False, verbose_name='Detalle requeridos')),
            ],
            options={
                'verbose_name': 'Tipo de salida',
                'verbose_name_plural': 'Tipos de salida',
                'db_table': 'output_type',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sap_code', models.CharField(max_length=10, unique=True, verbose_name='Código SAP')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('boxes_pre_pallet', models.IntegerField(default=0, verbose_name='Cajas por pallet')),
                ('useful_life', models.IntegerField(default=0, verbose_name='Vida útil')),
                ('bar_code', models.CharField(max_length=50, unique=True, verbose_name='Código de barras')),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo estándar')),
                ('pre_block', models.IntegerField(default=0, verbose_name='Pre-bloqueo')),
                ('block', models.IntegerField(default=0, verbose_name='Bloqueo')),
                ('pre_block_days', models.IntegerField(default=0, verbose_name='Días para pre-bloqueo')),
                ('pre_block_days_next', models.IntegerField(default=0, verbose_name='Días próximo pre-bloqueo')),
                ('block_days', models.IntegerField(default=0, verbose_name='Días para bloqueo')),
                ('code_feature', models.CharField(error_messages={'unique': 'Ya existe un producto con este código.'}, max_length=50, unique=True, verbose_name='Código')),
                ('division', models.CharField(max_length=50, verbose_name='División')),
                ('class_product', models.CharField(max_length=50, verbose_name='Clase')),
                ('size', models.CharField(max_length=50, verbose_name='Tamaño')),
                ('packaging', models.CharField(max_length=50, verbose_name='Empaque')),
                ('helectrolitos', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Helectrolitos')),
                ('hl_per_unit', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, verbose_name='HL por unidad')),
                ('concadenated_type', models.CharField(max_length=50, verbose_name='Tipo concadenado')),
                ('cost', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Costo')),
                ('description_sap', models.CharField(max_length=100, verbose_name='Descripción SAP')),
                ('lib_to_ton', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Lib a ton')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso')),
                ('ton', models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='Ton')),
                ('block_t1', models.IntegerField(default=0, verbose_name='Bloqueo T1')),
                ('days_not_accept_product', models.IntegerField(default=0, verbose_name='Días para no aceptar producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='TrailerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Trailer',
                'verbose_name_plural': 'Trailers',
                'db_table': 'trailer',
            },
        ),
        migrations.CreateModel(
            name='TransporterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('tractor', models.CharField(max_length=50, verbose_name='Tractor')),
                ('head', models.CharField(max_length=50, verbose_name='Cabezal')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'transporter',
            },
        ),
        migrations.CreateModel(
            name='OperatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('distributor_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('distributor_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.locationmodel', verbose_name='Localización')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'route',
                'unique_together': {('distributor_center', 'location', 'code')},
            },
        ),
    ]
