# Generated by Django 3.2.20 on 2023-09-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direction', models.CharField(max_length=50, null=True, verbose_name='Dirección')),
                ('country_code', models.CharField(max_length=5, null=True, verbose_name='Código de País')),
            ],
            options={
                'verbose_name': 'Centro de Distribución',
                'verbose_name_plural': 'Centros de Distribución',
                'db_table': 'distributor_center',
            },
        ),
    ]
