# Generated by Django 3.2.20 on 2023-09-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('label', models.CharField(blank=True, max_length=1, null=True)),
                ('initialDate', models.DateField(blank=True, null=True)),
                ('finalDate', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('distributor_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_distributor_center', to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'period',
            },
        ),
    ]
