# Generated by Django 3.2.20 on 2023-09-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='helectrolitos',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='Helectrolitos'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='hl_per_unit',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=14, verbose_name='HL por unidad'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='lib_to_ton',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='Lib a ton'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='ton',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='Ton'),
        ),
    ]
