# Generated by Django 3.2.20 on 2023-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20230925_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='cost',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12, verbose_name='Costo'),
        ),
    ]
