# Generated by Django 3.2.20 on 2023-09-21 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_periodmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodmodel',
            name='finalDate',
        ),
        migrations.RemoveField(
            model_name='periodmodel',
            name='year',
        ),
        migrations.AlterField(
            model_name='periodmodel',
            name='initialDate',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 20), null=True),
        ),
        migrations.AlterField(
            model_name='periodmodel',
            name='label',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True),
        ),
    ]
