# Generated by Django 3.2.20 on 2023-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_productmodel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputtypemodel',
            name='required_orders',
            field=models.BooleanField(default=False, verbose_name='Requiere pedidos'),
        ),
        migrations.AlterField(
            model_name='operatormodel',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='operatormodel',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Apellido'),
        ),
    ]


# la fecha es diferente