# Generated by Django 3.2.20 on 2023-09-23 02:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20230920_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_product', to='maintenance.productmodel', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='periodmodel',
            name='initialDate',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 23), null=True),
        ),
    ]
