# Generated by Django 3.2.20 on 2023-09-23 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20230920_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodmodel',
            name='initialDate',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 22), null=True),
        ),
    ]
