# Generated by Django 3.2.20 on 2023-09-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_trailermodel_transportermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('created_at_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Hora de Creación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sap_code', models.CharField(max_length=10, unique=True, verbose_name='Código SAP')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('boxes_pre_pallet', models.IntegerField(default=0, verbose_name='Cajas por pallet')),
                ('useful_life', models.IntegerField(default=0, verbose_name='Vida útil')),
                ('bar_code', models.CharField(max_length=50, unique=True, verbose_name='Código de barras')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
            },
        ),
    ]
