# Generated by Django 3.2.20 on 2023-09-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('created_at_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Hora de Creación')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('sap_code', models.CharField(max_length=10, unique=True, verbose_name='Código SAP')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'driver',
            },
        ),
    ]
