# Generated by Django 4.2.19 on 2025-03-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_auto_20240208_0556"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de registro"
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("code", models.CharField(max_length=5)),
                ("flag", models.CharField(max_length=150, null=True)),
            ],
            options={
                "verbose_name": "Pais",
                "verbose_name_plural": "Paises",
                "db_table": "country",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="distributorcenter",
            name="country",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="distributor_center_country",
                to="maintenance.countrymodel",
                verbose_name="País",
            ),
        ),
        migrations.AddField(
            model_name="locationmodel",
            name="country",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_country",
                to="maintenance.countrymodel",
                verbose_name="País",
            ),
        ),
    ]
