# Generated by Django 3.2.20 on 2023-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_periodmodel_initialdate'),
        ('maintenance', '0004_auto_20230922_2012'),
    ]

    operations = [
    ]
