# Generated by Django 3.2.20 on 2023-09-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_drivermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='distributor_center',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_distributor_center', to='maintenance.distributorcenter', verbose_name='Centro de Distribución'),
        ),
    ]
