# Generated by Django 3.2.20 on 2023-09-23 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_merge_20230923_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodmodel',
            name='initialDate',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 23), null=True),
        ),
    ]
