# Generated by Django 4.2.19 on 2026-03-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_countrymodel_distributorcenter_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorcenter',
            name='location_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ciudad / Ubicación'),
        ),
        migrations.AddField(
            model_name='distributorcenter',
            name='num_bays',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Bahías T2'),
        ),
        migrations.CreateModel(
            name='DCShiftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miercoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sabado'), ('SUN', 'Domingo')], max_length=3, verbose_name='Día de la Semana')),
                ('shift_name', models.CharField(help_text='Ej: TA, TB, TC', max_length=10, verbose_name='Nombre del Turno')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
            ],
            options={
                'verbose_name': 'Turno de CD',
                'verbose_name_plural': 'Turnos de CD',
                'db_table': 'dc_shift',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('distributor_center', 'day_of_week', 'shift_name')},
            },
        ),
    ]
