# Generated by Django 3.2.20 on 2023-09-24 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_periodmodel_initialdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='isOutput',
            field=models.BooleanField(default=False, verbose_name='Es de Salida'),
        ),
        migrations.AlterField(
            model_name='periodmodel',
            name='initialDate',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 24), null=True),
        ),
    ]
