# Generated by Django 3.2.20 on 2023-09-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_locationmodel_distributor_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='code',
            field=models.CharField(blank=True, error_messages={'unique': 'Ya existe una localización con este código'}, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
    ]
