# Generated by Django 3.2.20 on 2023-09-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_locationmodel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('created_at_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Hora de Creación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('required_details', models.BooleanField(default=False, verbose_name='Detalle requeridos')),
            ],
            options={
                'verbose_name': 'Tipo de salida',
                'verbose_name_plural': 'Tipos de salida',
                'db_table': 'output_type',
            },
        ),
    ]
