# Generated by Django 3.2.20 on 2023-09-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_auto_20230923_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='isOutput',
            new_name='is_output_product',
        ),
    ]
