# Generated by Django 3.2.20 on 2023-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_outputtypemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivermodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='drivermodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='operatormodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='operatormodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='outputtypemodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='outputtypemodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='routemodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='routemodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='trailermodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='trailermodel',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='transportermodel',
            name='created_at_date',
        ),
        migrations.RemoveField(
            model_name='transportermodel',
            name='created_at_time',
        ),
        migrations.AddField(
            model_name='drivermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='operatormodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='outputtypemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='trailermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='transportermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
    ]
