# Generated by Django 3.2.20 on 2023-09-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_rename_isoutput_productmodel_is_output_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='is_output_product',
            new_name='is_output',
        ),
    ]
