# Generated by Django 3.2.20 on 2023-09-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_auto_20230912_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailermodel',
            name='transporter',
        ),
    ]
