# Generated by Django 5.2 on 2025-04-16 02:57

import apps.document.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.document.models.document.document_upload_path)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('folder', models.CharField(default='general', max_length=50)),
                ('subfolder', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': '',
                'db_table': 'app_document',
            },
        ),
    ]
