# Generated by Django 3.2.20 on 2025-03-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmodel',
            name='extecion',
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
