# Generated by Django 4.2.19 on 2025-03-19 10:33

import apps.document.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_auto_20250303_2300"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentmodel",
            name="folder",
            field=models.CharField(default="general", max_length=50),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="subfolder",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="documentmodel",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.document.models.document.document_upload_path,
            ),
        ),
    ]
