# Generated by Django 3.2.20 on 2023-11-03 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0009_trackermodel_observation'),
        ('maintenance', '0003_alter_productmodel_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('quantity_available', models.IntegerField(default=0, verbose_name='Cantidad disponible')),
            ],
            options={
                'verbose_name': 'Detalle de orden',
                'verbose_name_plural': 'Detalles de ordenes',
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROCESS', 'En proceso'), ('COMPLETED', 'Completada')], default='PENDING', max_length=50, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_distributor_center', to='maintenance.distributorcenter', verbose_name='Centro de distribución')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_history', to='order.orderdetailmodel', verbose_name='Orden detalle')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history_tracker', to='tracker.trackermodel', verbose_name='Tracker')),
            ],
            options={
                'verbose_name': 'Historico de orden',
                'verbose_name_plural': 'Historicos de ordenes',
                'db_table': 'order_history',
            },
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='order.ordermodel', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_product', to='maintenance.productmodel', verbose_name='Producto'),
        ),
    ]
