# Generated by Django 3.2.20 on 2023-11-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_trackermodel_transfer_number'),
        ('order', '0002_ordermodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailmodel',
            name='tracker_detail_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_tracker_detail_product', to='tracker.trackerdetailproductmodel', verbose_name='Tracker detail product'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetailmodel',
            unique_together={('order', 'tracker_detail_product')},
        ),
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='product',
        ),
    ]
