# Generated by Django 3.2.20 on 2023-12-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20231117_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('fleet', models.CharField(choices=[('PROPIEDAD', 'Propiedad'), ('TERCERA', 'Tercera')], default='TERCERA', max_length=50, verbose_name='Flota')),
                ('type', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2')], default='T1', max_length=50, verbose_name='Tipo')),
                ('document_number', models.CharField(max_length=50, verbose_name='Numero de documento')),
                ('document', models.BinaryField(blank=True, null=True, verbose_name='Documento')),
                ('vehicle', models.CharField(max_length=50, verbose_name='Vehiculo')),
                ('document_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre documento')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='out_order', to='order.ordermodel', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Orden de salida',
                'verbose_name_plural': 'Ordenes de salida',
                'db_table': 'out_order',
            },
        ),
    ]
