# Generated by Django 4.2.16 on 2026-04-30 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_distributorcenter_location_city_and_more'),
        ('tracker', '0014_remove_trackermodel_archivo_and_more'),
        ('order', '0003_auto_20240208_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Cantidad total')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='Cantidad disponible')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='Cantidad reservada')),
            ],
            options={
                'verbose_name': 'Inventario de producto',
                'verbose_name_plural': 'Inventarios de productos',
                'db_table': 'product_inventory',
            },
        ),
        migrations.AlterUniqueTogether(
            name='orderdetailmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='distributor_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_distributor_center', to='maintenance.distributorcenter', verbose_name='Centro de distribución'),
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_product', to='maintenance.productmodel', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='tracker_detail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_tracker_detail_product', to='tracker.trackerdetailproductmodel', verbose_name='Tracker detail product'),
        ),
        migrations.AddConstraint(
            model_name='orderdetailmodel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product__isnull', True), ('tracker_detail_product__isnull', False)), models.Q(('product__isnull', False), ('tracker_detail_product__isnull', True)), _connector='OR'), name='order_detail_single_product_source'),
        ),
        migrations.AddField(
            model_name='productinventorymodel',
            name='distributor_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='maintenance.distributorcenter', verbose_name='Centro de distribución'),
        ),
        migrations.AddField(
            model_name='productinventorymodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='maintenance.productmodel', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='productinventorymodel',
            unique_together={('product', 'distributor_center', 'expiration_date')},
        ),
    ]
