# Generated by Django 4.2.19 on 2026-03-28 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0005_countrymodel_distributorcenter_country_and_more'),
        ('personnel', '0013_make_fields_optional_for_bulk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
            ],
            options={
                'verbose_name': 'Andén',
                'verbose_name_plural': 'Andenes',
                'db_table': 'truck_cycle_bay',
            },
        ),
        migrations.CreateModel(
            name='PalletComplexUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file', models.FileField(upload_to='truck_cycle/uploads/', verbose_name='Archivo')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('status', models.CharField(choices=[('PREVIEW', 'Vista Previa'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='PREVIEW', max_length=20, verbose_name='Estado')),
                ('errors_json', models.JSONField(blank=True, default=dict, verbose_name='Errores')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Filas')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_cycle_uploads', to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_cycle_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Carga de Pautas',
                'verbose_name_plural': 'Cargas de Pautas',
                'db_table': 'truck_cycle_upload',
            },
        ),
        migrations.CreateModel(
            name='PautaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('transport_number', models.CharField(max_length=20, verbose_name='Número de Transporte')),
                ('trip_number', models.CharField(blank=True, max_length=10, verbose_name='Número de Viaje')),
                ('route_code', models.CharField(blank=True, max_length=20, verbose_name='Código de Ruta')),
                ('total_boxes', models.PositiveIntegerField(default=0, verbose_name='Total de Cajas')),
                ('total_skus', models.PositiveIntegerField(default=0, verbose_name='Total de SKUs')),
                ('total_pallets', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Total de Tarimas')),
                ('complexity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Puntaje de Complejidad')),
                ('status', models.CharField(choices=[('PENDING_PICKING', 'Pendiente de Picking'), ('PICKING_ASSIGNED', 'Picking Asignado'), ('PICKING_IN_PROGRESS', 'Picking en Progreso'), ('PICKING_DONE', 'Picking Completado'), ('IN_BAY', 'En Andén'), ('PENDING_COUNT', 'Pendiente de Conteo'), ('COUNTING', 'Contando'), ('COUNTED', 'Contado'), ('PENDING_CHECKOUT', 'Pendiente de Checkout'), ('CHECKOUT_SECURITY', 'Checkout Seguridad'), ('CHECKOUT_OPS', 'Checkout Operaciones'), ('DISPATCHED', 'Despachado'), ('IN_RELOAD_QUEUE', 'En Cola de Recarga'), ('PENDING_RETURN', 'Pendiente de Devolución'), ('RETURN_PROCESSED', 'Devolución Procesada'), ('IN_AUDIT', 'En Auditoría'), ('AUDIT_COMPLETE', 'Auditoría Completa'), ('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada')], default='PENDING_PICKING', max_length=30, verbose_name='Estado')),
                ('operational_date', models.DateField(verbose_name='Fecha Operativa')),
                ('is_reload', models.BooleanField(default=False, verbose_name='Es Recarga')),
                ('reload_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Recargas')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
                ('parent_pauta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reload_pautas', to='truck_cycle.pautamodel', verbose_name='Pauta Padre')),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
                'db_table': 'truck_cycle_pauta',
                'ordering': ['-operational_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('pallet_type', models.CharField(choices=[('STANDARD', 'Estándar'), ('HALF', 'Media')], max_length=10, verbose_name='Tipo de Tarima')),
                ('pallet_spaces', models.PositiveIntegerField(verbose_name='Espacios de Tarima')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'db_table': 'truck_cycle_truck',
                'unique_together': {('code', 'distributor_center')},
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=20, verbose_name='Código SKU')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('division', models.CharField(blank=True, max_length=100, verbose_name='División')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('boxes_per_pallet', models.PositiveIntegerField(default=1, verbose_name='Cajas por Tarima')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_catalogs', to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
            ],
            options={
                'verbose_name': 'Catálogo de Producto',
                'verbose_name_plural': 'Catálogo de Productos',
                'db_table': 'truck_cycle_product_catalog',
                'unique_together': {('sku_code', 'distributor_center')},
            },
        ),
        migrations.CreateModel(
            name='PautaTimestampModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('T0_PICKING_START', 'T0 - Inicio de Picking'), ('T1_PICKING_END', 'T1 - Fin de Picking'), ('T2_BAY_ASSIGNED', 'T2 - Andén Asignado'), ('T3_LOADING_START', 'T3 - Inicio de Carga'), ('T4_LOADING_END', 'T4 - Fin de Carga'), ('T5_COUNT_START', 'T5 - Inicio de Conteo'), ('T6_COUNT_END', 'T6 - Fin de Conteo'), ('T7_CHECKOUT_SECURITY', 'T7 - Checkout Seguridad'), ('T8_CHECKOUT_OPS', 'T8 - Checkout Operaciones'), ('T9_DISPATCH', 'T9 - Despacho'), ('T10_ARRIVAL', 'T10 - Llegada'), ('T11_RELOAD_QUEUE', 'T11 - Cola de Recarga'), ('T12_RETURN_START', 'T12 - Inicio de Devolución'), ('T13_RETURN_END', 'T13 - Fin de Devolución'), ('T14_AUDIT_START', 'T14 - Inicio de Auditoría'), ('T15_AUDIT_END', 'T15 - Fin de Auditoría'), ('T16_CLOSE', 'T16 - Cierre'), ('T17_CANCELLED', 'T17 - Cancelada')], max_length=30, verbose_name='Tipo de Evento')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Marca de Tiempo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='truck_cycle.pautamodel', verbose_name='Pauta')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_cycle_timestamps', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Marca de Tiempo de Pauta',
                'verbose_name_plural': 'Marcas de Tiempo de Pauta',
                'db_table': 'truck_cycle_timestamp',
            },
        ),
        migrations.CreateModel(
            name='PautaProductDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=20, verbose_name='Código de Material')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('total_boxes', models.PositiveIntegerField(default=0, verbose_name='Total de Cajas')),
                ('full_pallets', models.PositiveIntegerField(default=0, verbose_name='Tarimas Completas')),
                ('fraction', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fracción')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='truck_cycle.pautamodel', verbose_name='Pauta')),
                ('product_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pauta_product_details', to='truck_cycle.productcatalogmodel', verbose_name='Catálogo de Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Producto de Pauta',
                'verbose_name_plural': 'Detalles de Producto de Pauta',
                'db_table': 'truck_cycle_pauta_product',
            },
        ),
        migrations.CreateModel(
            name='PautaPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('phase', models.CharField(choices=[('PRE_LOADING', 'Pre-Carga'), ('POST_LOADING', 'Post-Carga'), ('VERIFICATION', 'Verificación'), ('CHECKOUT', 'Checkout'), ('RETURN', 'Devolución'), ('AUDIT', 'Auditoría')], max_length=20, verbose_name='Fase')),
                ('photo', models.ImageField(upload_to='truck_cycle/photos/', verbose_name='Foto')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='truck_cycle.pautamodel', verbose_name='Pauta')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_cycle_photos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Foto de Pauta',
                'verbose_name_plural': 'Fotos de Pauta',
                'db_table': 'truck_cycle_photo',
            },
        ),
        migrations.AddField(
            model_name='pautamodel',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='truck_cycle.truckmodel', verbose_name='Camión'),
        ),
        migrations.AddField(
            model_name='pautamodel',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas', to='truck_cycle.palletcomplexuploadmodel', verbose_name='Carga'),
        ),
        migrations.CreateModel(
            name='PautaDeliveryDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=20, verbose_name='Código de Ruta')),
                ('delivery_number', models.CharField(max_length=30, verbose_name='Número de Entrega')),
                ('material_code', models.CharField(max_length=20, verbose_name='Código de Material')),
                ('delivery_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Entrega')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='truck_cycle.pautamodel', verbose_name='Pauta')),
            ],
            options={
                'verbose_name': 'Detalle de Entrega de Pauta',
                'verbose_name_plural': 'Detalles de Entrega de Pauta',
                'db_table': 'truck_cycle_pauta_delivery',
            },
        ),
        migrations.CreateModel(
            name='PautaBayAssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado en')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Liberado en')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_cycle_bay_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauta_assignments', to='truck_cycle.baymodel', verbose_name='Andén')),
                ('pauta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bay_assignment', to='truck_cycle.pautamodel', verbose_name='Pauta')),
            ],
            options={
                'verbose_name': 'Asignación de Andén',
                'verbose_name_plural': 'Asignaciones de Andén',
                'db_table': 'truck_cycle_bay_assignment',
            },
        ),
        migrations.CreateModel(
            name='PautaAssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PICKER', 'Picker'), ('COUNTER', 'Contador'), ('YARD_DRIVER', 'Conductor de Patio'), ('OPM', 'OPM'), ('VERIFIER', 'Verificador'), ('SECURITY', 'Seguridad'), ('OPERATIONS', 'Operaciones')], max_length=20, verbose_name='Rol')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado en')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_cycle_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='truck_cycle.pautamodel', verbose_name='Pauta')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_cycle_assignments', to='personnel.personnelprofile', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Asignación de Pauta',
                'verbose_name_plural': 'Asignaciones de Pauta',
                'db_table': 'truck_cycle_assignment',
            },
        ),
        migrations.CreateModel(
            name='PalletTicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('ticket_number', models.CharField(max_length=20, verbose_name='Número de Ticket')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='Código QR')),
                ('is_full_pallet', models.BooleanField(default=True, verbose_name='Tarima Completa')),
                ('box_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Cajas')),
                ('scanned', models.BooleanField(default=False, verbose_name='Escaneado')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='Escaneado en')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_tickets', to='truck_cycle.pautamodel', verbose_name='Pauta')),
            ],
            options={
                'verbose_name': 'Ticket de Tarima',
                'verbose_name_plural': 'Tickets de Tarima',
                'db_table': 'truck_cycle_pallet_ticket',
            },
        ),
        migrations.CreateModel(
            name='KPITargetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_type', models.CharField(choices=[('BOXES_PER_HOUR', 'Cajas por Hora'), ('COUNT_ACCURACY', 'Precisión de Conteo'), ('PICKING_ERROR_RATE', 'Tasa de Error de Picking'), ('LOADING_TIME', 'Tiempo de Carga'), ('DISPATCH_TIME', 'Tiempo de Despacho')], max_length=30, verbose_name='Tipo de KPI')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Meta')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad')),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Umbral de Alerta')),
                ('effective_from', models.DateField(verbose_name='Vigente Desde')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Vigente Hasta')),
                ('distributor_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='maintenance.distributorcenter', verbose_name='Centro de Distribución')),
            ],
            options={
                'verbose_name': 'Meta de KPI',
                'verbose_name_plural': 'Metas de KPI',
                'db_table': 'truck_cycle_kpi_target',
            },
        ),
        migrations.CreateModel(
            name='InconsistencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('phase', models.CharField(choices=[('VERIFICATION', 'Verificación'), ('CHECKOUT', 'Checkout'), ('RETURN', 'Devolución'), ('AUDIT', 'Auditoría')], max_length=20, verbose_name='Fase')),
                ('inconsistency_type', models.CharField(choices=[('FALTANTE', 'Faltante'), ('SOBRANTE', 'Sobrante'), ('CRUCE', 'Cruce'), ('DANADO', 'Dañado')], max_length=20, verbose_name='Tipo de Inconsistencia')),
                ('material_code', models.CharField(max_length=20, verbose_name='Código de Material')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Producto')),
                ('expected_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad Esperada')),
                ('actual_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad Real')),
                ('difference', models.IntegerField(default=0, verbose_name='Diferencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencies', to='truck_cycle.pautamodel', verbose_name='Pauta')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_cycle_inconsistencies', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Inconsistencia',
                'verbose_name_plural': 'Inconsistencias',
                'db_table': 'truck_cycle_inconsistency',
            },
        ),
        migrations.CreateModel(
            name='CheckoutValidationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_validated', models.BooleanField(default=False, verbose_name='Validado por Seguridad')),
                ('security_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validado por Seguridad en')),
                ('ops_validated', models.BooleanField(default=False, verbose_name='Validado por Operaciones')),
                ('ops_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validado por Operaciones en')),
                ('exit_pass_consumables', models.BooleanField(default=False, verbose_name='Pase de Salida de Consumibles')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('ops_validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_validations', to='personnel.personnelprofile', verbose_name='Validador de Operaciones')),
                ('pauta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_validation', to='truck_cycle.pautamodel', verbose_name='Pauta')),
                ('security_validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_validations', to='personnel.personnelprofile', verbose_name='Validador de Seguridad')),
            ],
            options={
                'verbose_name': 'Validación de Checkout',
                'verbose_name_plural': 'Validaciones de Checkout',
                'db_table': 'truck_cycle_checkout',
            },
        ),
    ]
