# Generated by Django 4.2.19 on 2026-04-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_cycle', '0002_moving_to_bay_and_reentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baymodel',
            options={'ordering': ['row', 'column', 'code'], 'verbose_name': 'Andén', 'verbose_name_plural': 'Andenes'},
        ),
        migrations.AddField(
            model_name='baymodel',
            name='column',
            field=models.PositiveIntegerField(default=0, help_text='Columna en el grid visual del estacionamiento (0-indexed).', verbose_name='Columna'),
        ),
        migrations.AddField(
            model_name='baymodel',
            name='row',
            field=models.PositiveIntegerField(default=0, help_text='Fila en el grid visual del estacionamiento (0-indexed).', verbose_name='Fila'),
        ),
    ]
