# Generated by Django 4.2.19 on 2026-04-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_cycle', '0003_alter_baymodel_options_baymodel_column_baymodel_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='pautamodel',
            name='assembled_fractions',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de tarimas parciales armadas (no llenas).', verbose_name='Fracciones Armadas'),
        ),
    ]
