# Generated by Django 4.2.19 on 2026-04-20 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_alter_personnelprofile_position_type_and_more'),
        ('truck_cycle', '0004_pautamodel_assembled_fractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckmodel',
            name='primary_driver',
            field=models.ForeignKey(blank=True, help_text='Chofer vendedor asignado por defecto a este camión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_trucks', to='personnel.personnelprofile', verbose_name='Chofer asignado'),
        ),
        migrations.AlterField(
            model_name='pautaassignmentmodel',
            name='role',
            field=models.CharField(choices=[('PICKER', 'Picker'), ('COUNTER', 'Contador'), ('YARD_DRIVER', 'Conductor de Patio'), ('DELIVERY_DRIVER', 'Chofer Vendedor'), ('OPM', 'OPM'), ('VERIFIER', 'Verificador'), ('SECURITY', 'Seguridad'), ('OPERATIONS', 'Operaciones')], max_length=20, verbose_name='Rol'),
        ),
    ]
